namespace PDFPatcher.Functions
{
	partial class AddPdfObjectForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddPdfObjectForm));
            this._OkButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this._ObjectNameBox = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this._TextValueBox = new System.Windows.Forms.TextBox();
            this._NumericValueBox = new System.Windows.Forms.TextBox();
            this._BooleanValueBox = new System.Windows.Forms.CheckBox();
            this._NameValueBox = new System.Windows.Forms.TextBox();
            this._CreateAsRefBox = new System.Windows.Forms.CheckBox();
            this.SuspendLayout();
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // _CancelButton
            // 
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // _ObjectNameBox
            // 
            resources.ApplyResources(this._ObjectNameBox, "_ObjectNameBox");
            this._ObjectNameBox.Name = "_ObjectNameBox";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // _TextValueBox
            // 
            this._TextValueBox.AcceptsReturn = true;
            this._TextValueBox.AcceptsTab = true;
            resources.ApplyResources(this._TextValueBox, "_TextValueBox");
            this._TextValueBox.Name = "_TextValueBox";
            // 
            // _NumericValueBox
            // 
            resources.ApplyResources(this._NumericValueBox, "_NumericValueBox");
            this._NumericValueBox.Name = "_NumericValueBox";
            // 
            // _BooleanValueBox
            // 
            resources.ApplyResources(this._BooleanValueBox, "_BooleanValueBox");
            this._BooleanValueBox.Name = "_BooleanValueBox";
            this._BooleanValueBox.UseVisualStyleBackColor = true;
            // 
            // _NameValueBox
            // 
            resources.ApplyResources(this._NameValueBox, "_NameValueBox");
            this._NameValueBox.Name = "_NameValueBox";
            // 
            // _CreateAsRefBox
            // 
            resources.ApplyResources(this._CreateAsRefBox, "_CreateAsRefBox");
            this._CreateAsRefBox.Name = "_CreateAsRefBox";
            this._CreateAsRefBox.UseVisualStyleBackColor = true;
            // 
            // AddPdfObjectForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._CreateAsRefBox);
            this.Controls.Add(this._NameValueBox);
            this.Controls.Add(this._BooleanValueBox);
            this.Controls.Add(this._NumericValueBox);
            this.Controls.Add(this._TextValueBox);
            this.Controls.Add(this.label2);
            this.Controls.Add(this._ObjectNameBox);
            this.Controls.Add(this.label1);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "AddPdfObjectForm";
            this.Load += new System.EventHandler(this.AddPdfObjectForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _OkButton;
		private System.Windows.Forms.Button _CancelButton;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.TextBox _ObjectNameBox;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.TextBox _TextValueBox;
		private System.Windows.Forms.TextBox _NumericValueBox;
		private System.Windows.Forms.CheckBox _BooleanValueBox;
		private System.Windows.Forms.TextBox _NameValueBox;
		private System.Windows.Forms.CheckBox _CreateAsRefBox;
	}
}

