//------------------------------------------------ ------------------------------
// <auto-generated>
// This code is generated by the tool.
// Runtime version: 4.0.30319.42000
//
// Changes to this file may cause incorrect behavior, and if
// Regenerate the code, these changes will be lost.
// </auto-generated>
//------------------------------------------------ ------------------------------

namespace PDFPatcher
{
    using System;


    /// <summary>
    /// A strongly typed resource class for finding localized strings, etc.
    /// </summary>
    // This class is created by StronglyTypedResourceBuilder
    // Classes are automatically generated by tools like ResGen or Visual Studio.
    // To add or remove members, edit the .ResX file and rerun ResGen
    // (with /str as a command option), or rebuild the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration()
        {
        }

        /// <summary>
        ///   Returns a cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFPatcher.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the CurrentUICulture property of the current thread
        /// Overrides the CurrentUICulture property of the current thread.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Find localized strings like bookmark text .
        /// </summary>
        internal static string BookmarkText
        {
            get
            {
                return ResourceManager.GetString("BookmarkText", resourceCulture);
            }
        }

        /// <summary>
        ///   Look for localized strings like custom toolbar buttons .
        /// </summary>
        internal static string CustomToolbarButtons
        {
            get
            {
                return ResourceManager.GetString("CustomToolbarButtons", resourceCulture);
            }
        }

        /// <summary>
        ///   Look for localized strings like document properties .
        /// </summary>
        internal static string DocInfo
        {
            get
            {
                return ResourceManager.GetString("DocInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Find localized strings like body text .
        /// </summary>
        internal static string DocText
        {
            get
            {
                return ResourceManager.GetString("DocText", resourceCulture);
            }
        }

        /// <summary>
        ///   Look for localized strings like encoding.
        /// </summary>
        internal static string Encodings
        {
            get
            {
                return ResourceManager.GetString("Encodings", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to exporting the image directory.
        /// </summary>
        internal static string Folders
        {
            get
            {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string of similar information files.
        /// </summary>
        internal static string InfoFiles
        {
            get
            {
                return ResourceManager.GetString("InfoFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to reducing the memory.
        /// </summary>
        internal static string OptimalMemoryUsage
        {
            get
            {
                return ResourceManager.GetString("OptimalMemoryUsage", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to optimizing processing efficiency.
        /// </summary>
        internal static string OptimalSpeed
        {
            get
            {
                return ResourceManager.GetString("OptimalSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string of similar processing options.
        /// </summary>
        internal static string Options
        {
            get
            {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string of similar paths.
        /// </summary>
        internal static string Path
        {
            get
            {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to a PDF read mode.
        /// </summary>
        internal static string PdfLoadMode
        {
            get
            {
                return ResourceManager.GetString("PdfLoadMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to a PDF reader path.
        /// </summary>
        internal static string PdfReaderPath
        {
            get
            {
                return ResourceManager.GetString("PdfReaderPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string of similar historical documents.
        /// </summary>
        internal static string RecentFiles
        {
            get
            {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to replacement text.
        /// </summary>
        internal static string ReplaceItems
        {
            get
            {
                return ResourceManager.GetString("ReplaceItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string of similar configuration files.
        /// </summary>
        internal static string Root
        {
            get
            {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to a save program configured.
        /// </summary>
        internal static string SaveAppSettings
        {
            get
            {
                return ResourceManager.GetString("SaveAppSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to looking for text.
        /// </summary>
        internal static string SearchItems
        {
            get
            {
                return ResourceManager.GetString("SearchItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to the input file.
        /// </summary>
        internal static string SourceFiles
        {
            get
            {
                return ResourceManager.GetString("SourceFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Find a localized string similar to the target file.
        /// </summary>
        internal static string TargetFiles
        {
            get
            {
                return ResourceManager.GetString("TargetFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Find similar versions of localized strings.
        /// </summary>
        internal static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
