//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFPatcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFPatcher.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark Text.
        /// </summary>
        internal static string BookmarkText {
            get {
                return ResourceManager.GetString("BookmarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Toolbar Buttons.
        /// </summary>
        internal static string CustomToolbarButtons {
            get {
                return ResourceManager.GetString("CustomToolbarButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        internal static string DocInfo {
            get {
                return ResourceManager.GetString("DocInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document text.
        /// </summary>
        internal static string DocText {
            get {
                return ResourceManager.GetString("DocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodings.
        /// </summary>
        internal static string Encodings {
            get {
                return ResourceManager.GetString("Encodings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Files.
        /// </summary>
        internal static string InfoFiles {
            get {
                return ResourceManager.GetString("InfoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal Memory Usage.
        /// </summary>
        internal static string OptimalMemoryUsage {
            get {
                return ResourceManager.GetString("OptimalMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal Speed.
        /// </summary>
        internal static string OptimalSpeed {
            get {
                return ResourceManager.GetString("OptimalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Load Mode.
        /// </summary>
        internal static string PdfLoadMode {
            get {
                return ResourceManager.GetString("PdfLoadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Reader Path.
        /// </summary>
        internal static string PdfReaderPath {
            get {
                return ResourceManager.GetString("PdfReaderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        internal static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Items.
        /// </summary>
        internal static string ReplaceItems {
            get {
                return ResourceManager.GetString("ReplaceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save App Settings.
        /// </summary>
        internal static string SaveAppSettings {
            get {
                return ResourceManager.GetString("SaveAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Items.
        /// </summary>
        internal static string SearchItems {
            get {
                return ResourceManager.GetString("SearchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Files.
        /// </summary>
        internal static string SourceFiles {
            get {
                return ResourceManager.GetString("SourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Files.
        /// </summary>
        internal static string TargetFiles {
            get {
                return ResourceManager.GetString("TargetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
