namespace PDFPatcher
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up all resources in use.
        /// </summary>
        /// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Windows Forms designer

        /// <summary>
        /// Designer supports required methods - Don't
        /// use a code editor to modify the content of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.ToolStripMenuItem _Select;
            System.Windows.Forms.ToolStripMenuItem _Copy;
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            System.Windows.Forms.ToolStripMenuItem _Delete;
            System.Windows.Forms.ToolStripSeparator toolStripSeparator3;
            System.Windows.Forms.ToolStripMenuItem _SelectAllPdfFiles;
            System.Windows.Forms.ToolStripMenuItem _SelectAllImages;
            System.Windows.Forms.ToolStripMenuItem _SelectAllFolders;
            System.Windows.Forms.ToolStripSeparator _ItemTypeSeparator;
            System.Windows.Forms.ToolStripMenuItem _SelectAll;
            System.Windows.Forms.ToolStripMenuItem _InvertSelect;
            System.Windows.Forms.ToolStripMenuItem _SelectNone;
            System.Windows.Forms.ToolStripMenuItem _ToolBox;
            System.Windows.Forms.ToolStripMenuItem toolStripMenuItem23;
            System.Windows.Forms.ToolStripMenuItem _Patcher;
            System.Windows.Forms.ToolStripMenuItem _Merger;
            System.Windows.Forms.ToolStripMenuItem _Rename;
            System.Windows.Forms.ToolStripMenuItem _OcrImages;
            System.Windows.Forms.ToolStripMenuItem _GenerateBookmark;
            System.Windows.Forms.ToolStripMenuItem _InfoExchanger;
            System.Windows.Forms.ToolStripMenuItem _Imaging;
            System.Windows.Forms.ToolStripMenuItem _Extract;
            System.Windows.Forms.ToolStripMenuItem _ExtractImages;
            System.Windows.Forms.ToolStripMenuItem _RenderPages;
            System.Windows.Forms.ToolStripMenuItem _Explorer;
            System.Windows.Forms.ToolStripMenuItem _ExportInfoFile;
            System.Windows.Forms.ToolStripSeparator toolStripSeparator5;
            System.Windows.Forms.ToolStripMenuItem _ShowGeneralToolbar;
            System.Windows.Forms.ToolStripMenuItem _CustomizeToolbarCommand;
            System.Windows.Forms.ToolStripMenuItem _LogWindow;
            System.Windows.Forms.ToolStripMenuItem _Help;
            System.Windows.Forms.ToolStripMenuItem _CreateShortcut;
            System.Windows.Forms.ToolStripMenuItem _CheckUpdate;
            System.Windows.Forms.ToolStripMenuItem _VisitHomePage;
            System.Windows.Forms.ToolStripMenuItem _About;
            System.Windows.Forms.ToolStripMenuItem _Open;
            System.Windows.Forms.ToolStripMenuItem dummyToolStripMenuItem;
            System.Windows.Forms.ToolStripMenuItem _ImportBookmark;
            System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
            System.Windows.Forms.ToolStripMenuItem _Action;
            System.Windows.Forms.ToolStripMenuItem _SaveBookmark;
            System.Windows.Forms.ToolStripMenuItem _SaveAsInfoFile;
            System.Windows.Forms.ToolStripSeparator _configSeparator;
            System.Windows.Forms.ToolStripMenuItem _AppOptions;
            System.Windows.Forms.ToolStripMenuItem _RestoreOptions;
            System.Windows.Forms.ToolStripMenuItem _SaveOptions;
            System.Windows.Forms.ToolStripSeparator toolStripSeparator11;
            System.Windows.Forms.ToolStripMenuItem _Exit;
            System.Windows.Forms.ToolStripMenuItem _Close;
            System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
            System.Windows.Forms.ToolStripMenuItem _Options;
            System.Windows.Forms.ToolStripButton _CustomizeToolbar;
            System.Windows.Forms.ToolStripMenuItem _Properties;
            this.toolStripSeparator14 = new System.Windows.Forms.ToolStripSeparator();
            this._ToolTip = new System.Windows.Forms.ToolTip(this.components);
            this._SaveConfigDialog = new System.Windows.Forms.SaveFileDialog();
            this._OpenConfigDialog = new System.Windows.Forms.OpenFileDialog();
            this._MainMenu = new System.Windows.Forms.MenuStrip();
            this._File = new System.Windows.Forms.ToolStripMenuItem();
            this._RecentFiles = new System.Windows.Forms.ToolStripMenuItem();
            this._ResetOptions = new System.Windows.Forms.ToolStripMenuItem();
            this._OpenPdfDialog = new System.Windows.Forms.OpenFileDialog();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this._MainStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this._GeneralToolbar = new System.Windows.Forms.ToolStrip();
            this._FunctionContainer = new TradeWright.UI.Forms.TabControlExtra();
            _Select = new System.Windows.Forms.ToolStripMenuItem();
            _Copy = new System.Windows.Forms.ToolStripMenuItem();
            _Delete = new System.Windows.Forms.ToolStripMenuItem();
            toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            _SelectAllPdfFiles = new System.Windows.Forms.ToolStripMenuItem();
            _SelectAllImages = new System.Windows.Forms.ToolStripMenuItem();
            _SelectAllFolders = new System.Windows.Forms.ToolStripMenuItem();
            _ItemTypeSeparator = new System.Windows.Forms.ToolStripSeparator();
            _SelectAll = new System.Windows.Forms.ToolStripMenuItem();
            _InvertSelect = new System.Windows.Forms.ToolStripMenuItem();
            _SelectNone = new System.Windows.Forms.ToolStripMenuItem();
            _ToolBox = new System.Windows.Forms.ToolStripMenuItem();
            toolStripMenuItem23 = new System.Windows.Forms.ToolStripMenuItem();
            _Patcher = new System.Windows.Forms.ToolStripMenuItem();
            _Merger = new System.Windows.Forms.ToolStripMenuItem();
            _Rename = new System.Windows.Forms.ToolStripMenuItem();
            _OcrImages = new System.Windows.Forms.ToolStripMenuItem();
            _GenerateBookmark = new System.Windows.Forms.ToolStripMenuItem();
            _InfoExchanger = new System.Windows.Forms.ToolStripMenuItem();
            _Imaging = new System.Windows.Forms.ToolStripMenuItem();
            _Extract = new System.Windows.Forms.ToolStripMenuItem();
            _ExtractImages = new System.Windows.Forms.ToolStripMenuItem();
            _RenderPages = new System.Windows.Forms.ToolStripMenuItem();
            _Explorer = new System.Windows.Forms.ToolStripMenuItem();
            _ExportInfoFile = new System.Windows.Forms.ToolStripMenuItem();
            toolStripSeparator5 = new System.Windows.Forms.ToolStripSeparator();
            _ShowGeneralToolbar = new System.Windows.Forms.ToolStripMenuItem();
            _CustomizeToolbarCommand = new System.Windows.Forms.ToolStripMenuItem();
            _LogWindow = new System.Windows.Forms.ToolStripMenuItem();
            _Help = new System.Windows.Forms.ToolStripMenuItem();
            _CreateShortcut = new System.Windows.Forms.ToolStripMenuItem();
            _CheckUpdate = new System.Windows.Forms.ToolStripMenuItem();
            _VisitHomePage = new System.Windows.Forms.ToolStripMenuItem();
            _About = new System.Windows.Forms.ToolStripMenuItem();
            _Open = new System.Windows.Forms.ToolStripMenuItem();
            dummyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            _ImportBookmark = new System.Windows.Forms.ToolStripMenuItem();
            toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            _Action = new System.Windows.Forms.ToolStripMenuItem();
            _SaveBookmark = new System.Windows.Forms.ToolStripMenuItem();
            _SaveAsInfoFile = new System.Windows.Forms.ToolStripMenuItem();
            _configSeparator = new System.Windows.Forms.ToolStripSeparator();
            _AppOptions = new System.Windows.Forms.ToolStripMenuItem();
            _RestoreOptions = new System.Windows.Forms.ToolStripMenuItem();
            _SaveOptions = new System.Windows.Forms.ToolStripMenuItem();
            toolStripSeparator11 = new System.Windows.Forms.ToolStripSeparator();
            _Exit = new System.Windows.Forms.ToolStripMenuItem();
            _Close = new System.Windows.Forms.ToolStripMenuItem();
            toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            _Options = new System.Windows.Forms.ToolStripMenuItem();
            _CustomizeToolbar = new System.Windows.Forms.ToolStripButton();
            _Properties = new System.Windows.Forms.ToolStripMenuItem();
            this._MainMenu.SuspendLayout();
            this.statusStrip1.SuspendLayout();
            this._GeneralToolbar.SuspendLayout();
            this.SuspendLayout();
            // 
            // _Select
            // 
            _Select.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            _Select.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            _Copy,
            _Delete,
            toolStripSeparator3,
            _SelectAllPdfFiles,
            _SelectAllImages,
            _SelectAllFolders,
            _ItemTypeSeparator,
            _SelectAll,
            _InvertSelect,
            _SelectNone});
            resources.ApplyResources(_Select, "_Select");
            _Select.Name = "_Select";
            _Select.DropDownOpening += new System.EventHandler(this.MenuOpening);
            _Select.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.MenuCommand);
            // 
            // _Copy
            // 
            resources.ApplyResources(_Copy, "_Copy");
            _Copy.Name = "_Copy";
            // 
            // _Delete
            // 
            resources.ApplyResources(_Delete, "_Delete");
            _Delete.Name = "_Delete";
            // 
            // toolStripSeparator3
            // 
            toolStripSeparator3.Name = "toolStripSeparator3";
            resources.ApplyResources(toolStripSeparator3, "toolStripSeparator3");
            // 
            // _SelectAllPdfFiles
            // 
            resources.ApplyResources(_SelectAllPdfFiles, "_SelectAllPdfFiles");
            _SelectAllPdfFiles.Name = "_SelectAllPdfFiles";
            // 
            // _SelectAllImages
            // 
            resources.ApplyResources(_SelectAllImages, "_SelectAllImages");
            _SelectAllImages.Name = "_SelectAllImages";
            // 
            // _SelectAllFolders
            // 
            resources.ApplyResources(_SelectAllFolders, "_SelectAllFolders");
            _SelectAllFolders.Name = "_SelectAllFolders";
            // 
            // _ItemTypeSeparator
            // 
            _ItemTypeSeparator.Name = "_ItemTypeSeparator";
            resources.ApplyResources(_ItemTypeSeparator, "_ItemTypeSeparator");
            // 
            // _SelectAll
            // 
            resources.ApplyResources(_SelectAll, "_SelectAll");
            _SelectAll.Name = "_SelectAll";
            // 
            // _InvertSelect
            // 
            _InvertSelect.Name = "_InvertSelect";
            resources.ApplyResources(_InvertSelect, "_InvertSelect");
            // 
            // _SelectNone
            // 
            _SelectNone.Name = "_SelectNone";
            resources.ApplyResources(_SelectNone, "_SelectNone");
            // 
            // _ToolBox
            // 
            _ToolBox.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            _ToolBox.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            toolStripMenuItem23,
            _Imaging,
            _Explorer,
            _ExportInfoFile,
            toolStripSeparator5,
            _ShowGeneralToolbar,
            _CustomizeToolbarCommand,
            _LogWindow});
            resources.ApplyResources(_ToolBox, "_ToolBox");
            _ToolBox.Name = "_ToolBox";
            _ToolBox.DropDownOpening += new System.EventHandler(this.MenuOpening);
            _ToolBox.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.MenuCommand);
            // 
            // toolStripMenuItem23
            // 
            toolStripMenuItem23.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            _Patcher,
            _Merger,
            _Rename,
            _OcrImages,
            _GenerateBookmark,
            _InfoExchanger});
            toolStripMenuItem23.Name = "toolStripMenuItem23";
            resources.ApplyResources(toolStripMenuItem23, "toolStripMenuItem23");
            toolStripMenuItem23.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.MenuCommand);
            // 
            // _Patcher
            // 
            resources.ApplyResources(_Patcher, "_Patcher");
            _Patcher.Name = "_Patcher";
            _Patcher.Tag = "Patcher";
            // 
            // _Merger
            // 
            resources.ApplyResources(_Merger, "_Merger");
            _Merger.Name = "_Merger";
            _Merger.Tag = "Merger";
            // 
            // _Rename
            // 
            resources.ApplyResources(_Rename, "_Rename");
            _Rename.Name = "_Rename";
            _Rename.Tag = "Rename";
            // 
            // _OcrImages
            // 
            resources.ApplyResources(_OcrImages, "_OcrImages");
            _OcrImages.Name = "_OcrImages";
            _OcrImages.Tag = "Ocr";
            // 
            // _GenerateBookmark
            // 
            _GenerateBookmark.Image = global::PDFPatcher.Properties.Resources.AutoBookmark;
            _GenerateBookmark.Name = "_GenerateBookmark";
            resources.ApplyResources(_GenerateBookmark, "_GenerateBookmark");
            _GenerateBookmark.Tag = "BookmarkGenerator";
            // 
            // _InfoExchanger
            // 
            resources.ApplyResources(_InfoExchanger, "_InfoExchanger");
            _InfoExchanger.Name = "_InfoExchanger";
            _InfoExchanger.Tag = "InfoExchanger";
            // 
            // _Imaging
            // 
            _Imaging.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            _Extract,
            _ExtractImages,
            _RenderPages});
            _Imaging.Name = "_Imaging";
            resources.ApplyResources(_Imaging, "_Imaging");
            _Imaging.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.MenuCommand);
            // 
            // _Extract
            // 
            resources.ApplyResources(_Extract, "_Extract");
            _Extract.Name = "_Extract";
            _Extract.Tag = "ExtractPages";
            // 
            // _ExtractImages
            // 
            resources.ApplyResources(_ExtractImages, "_ExtractImages");
            _ExtractImages.Name = "_ExtractImages";
            _ExtractImages.Tag = "ExtractImages";
            // 
            // _RenderPages
            // 
            _RenderPages.Image = global::PDFPatcher.Properties.Resources.RenderDocument;
            _RenderPages.Name = "_RenderPages";
            resources.ApplyResources(_RenderPages, "_RenderPages");
            _RenderPages.Tag = "RenderPages";
            // 
            // _Explorer
            // 
            resources.ApplyResources(_Explorer, "_Explorer");
            _Explorer.Name = "_Explorer";
            _Explorer.Tag = "Inspector";
            // 
            // _ExportInfoFile
            // 
            resources.ApplyResources(_ExportInfoFile, "_ExportInfoFile");
            _ExportInfoFile.Name = "_ExportInfoFile";
            _ExportInfoFile.Tag = "InfoExchanger";
            // 
            // toolStripSeparator5
            // 
            toolStripSeparator5.Name = "toolStripSeparator5";
            resources.ApplyResources(toolStripSeparator5, "toolStripSeparator5");
            // 
            // _ShowGeneralToolbar
            // 
            _ShowGeneralToolbar.Name = "_ShowGeneralToolbar";
            resources.ApplyResources(_ShowGeneralToolbar, "_ShowGeneralToolbar");
            // 
            // _CustomizeToolbarCommand
            // 
            resources.ApplyResources(_CustomizeToolbarCommand, "_CustomizeToolbarCommand");
            _CustomizeToolbarCommand.Name = "_CustomizeToolbarCommand";
            // 
            // _LogWindow
            // 
            resources.ApplyResources(_LogWindow, "_LogWindow");
            _LogWindow.Name = "_LogWindow";
            _LogWindow.Tag = "";
            // 
            // _Help
            // 
            _Help.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            _CreateShortcut,
            this.toolStripSeparator14,
            _CheckUpdate,
            _VisitHomePage,
            _About});
            _Help.Name = "_Help";
            resources.ApplyResources(_Help, "_Help");
            _Help.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.MenuCommand);
            // 
            // _CreateShortcut
            // 
            resources.ApplyResources(_CreateShortcut, "_CreateShortcut");
            _CreateShortcut.Name = "_CreateShortcut";
            // 
            // toolStripSeparator14
            // 
            this.toolStripSeparator14.Name = "toolStripSeparator14";
            resources.ApplyResources(this.toolStripSeparator14, "toolStripSeparator14");
            // 
            // _CheckUpdate
            // 
            resources.ApplyResources(_CheckUpdate, "_CheckUpdate");
            _CheckUpdate.Name = "_CheckUpdate";
            // 
            // _VisitHomePage
            // 
            resources.ApplyResources(_VisitHomePage, "_VisitHomePage");
            _VisitHomePage.Name = "_VisitHomePage";
            // 
            // _About
            // 
            resources.ApplyResources(_About, "_About");
            _About.Name = "_About";
            _About.Tag = "About";
            // 
            // _Open
            // 
            resources.ApplyResources(_Open, "_Open");
            _Open.Name = "_Open";
            // 
            // dummyToolStripMenuItem
            // 
            resources.ApplyResources(dummyToolStripMenuItem, "dummyToolStripMenuItem");
            dummyToolStripMenuItem.Name = "dummyToolStripMenuItem";
            // 
            // _ImportBookmark
            // 
            resources.ApplyResources(_ImportBookmark, "_ImportBookmark");
            _ImportBookmark.Name = "_ImportBookmark";
            // 
            // toolStripSeparator2
            // 
            toolStripSeparator2.Name = "toolStripSeparator2";
            resources.ApplyResources(toolStripSeparator2, "toolStripSeparator2");
            // 
            // _Action
            // 
            _Action.Image = global::PDFPatcher.Properties.Resources.Save;
            _Action.Name = "_Action";
            resources.ApplyResources(_Action, "_Action");
            // 
            // _SaveBookmark
            // 
            _SaveBookmark.Image = global::PDFPatcher.Properties.Resources.ExportInfoFile;
            _SaveBookmark.Name = "_SaveBookmark";
            resources.ApplyResources(_SaveBookmark, "_SaveBookmark");
            // 
            // _SaveAsInfoFile
            // 
            resources.ApplyResources(_SaveAsInfoFile, "_SaveAsInfoFile");
            _SaveAsInfoFile.Name = "_SaveAsInfoFile";
            // 
            // _configSeparator
            // 
            _configSeparator.Name = "_configSeparator";
            resources.ApplyResources(_configSeparator, "_configSeparator");
            // 
            // _AppOptions
            // 
            resources.ApplyResources(_AppOptions, "_AppOptions");
            _AppOptions.Name = "_AppOptions";
            _AppOptions.Tag = "Options";
            // 
            // _RestoreOptions
            // 
            _RestoreOptions.Name = "_RestoreOptions";
            resources.ApplyResources(_RestoreOptions, "_RestoreOptions");
            // 
            // _SaveOptions
            // 
            _SaveOptions.Name = "_SaveOptions";
            resources.ApplyResources(_SaveOptions, "_SaveOptions");
            // 
            // toolStripSeparator11
            // 
            toolStripSeparator11.Name = "toolStripSeparator11";
            resources.ApplyResources(toolStripSeparator11, "toolStripSeparator11");
            // 
            // _Exit
            // 
            _Exit.Name = "_Exit";
            resources.ApplyResources(_Exit, "_Exit");
            // 
            // _Close
            // 
            _Close.Image = global::PDFPatcher.Properties.Resources.Close;
            _Close.Name = "_Close";
            resources.ApplyResources(_Close, "_Close");
            // 
            // toolStripSeparator1
            // 
            toolStripSeparator1.Name = "toolStripSeparator1";
            resources.ApplyResources(toolStripSeparator1, "toolStripSeparator1");
            // 
            // _Options
            // 
            resources.ApplyResources(_Options, "_Options");
            _Options.Name = "_Options";
            _Options.Tag = "PatcherOptions";
            // 
            // _CustomizeToolbar
            // 
            _CustomizeToolbar.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            resources.ApplyResources(_CustomizeToolbar, "_CustomizeToolbar");
            _CustomizeToolbar.Name = "_CustomizeToolbar";
            // 
            // _Properties
            // 
            _Properties.Image = global::PDFPatcher.Properties.Resources.Property;
            _Properties.Name = "_Properties";
            resources.ApplyResources(_Properties, "_Properties");
            // 
            // _ToolTip
            // 
            this._ToolTip.IsBalloon = true;
            this._ToolTip.ShowAlways = true;
            // 
            // _SaveConfigDialog
            // 
            this._SaveConfigDialog.DefaultExt = "json";
            resources.ApplyResources(this._SaveConfigDialog, "_SaveConfigDialog");
            // 
            // _OpenConfigDialog
            // 
            this._OpenConfigDialog.DefaultExt = "json";
            resources.ApplyResources(this._OpenConfigDialog, "_OpenConfigDialog");
            // 
            // _MainMenu
            // 
            this._MainMenu.ImageScalingSize = new System.Drawing.Size(20, 20);
            this._MainMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._File,
            _ToolBox,
            _Select,
            _Help});
            resources.ApplyResources(this._MainMenu, "_MainMenu");
            this._MainMenu.Name = "_MainMenu";
            // 
            // _File
            // 
            this._File.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this._File.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            _Open,
            this._RecentFiles,
            _ImportBookmark,
            toolStripSeparator1,
            _Close,
            toolStripSeparator2,
            _Action,
            _SaveBookmark,
            _SaveAsInfoFile,
            _configSeparator,
            _Properties,
            _Options,
            this._ResetOptions,
            _AppOptions,
            _RestoreOptions,
            _SaveOptions,
            toolStripSeparator11,
            _Exit});
            resources.ApplyResources(this._File, "_File");
            this._File.Name = "_File";
            this._File.DropDownOpening += new System.EventHandler(this.MenuOpening);
            this._File.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.MenuCommand);
            // 
            // _RecentFiles
            // 
            this._RecentFiles.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            dummyToolStripMenuItem});
            this._RecentFiles.Name = "_RecentFiles";
            resources.ApplyResources(this._RecentFiles, "_RecentFiles");
            this._RecentFiles.DropDownOpening += new System.EventHandler(this.RecentFileMenuOpening);
            this._RecentFiles.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.MenuCommand);
            // 
            // _ResetOptions
            // 
            resources.ApplyResources(this._ResetOptions, "_ResetOptions");
            this._ResetOptions.Name = "_ResetOptions";
            // 
            // _OpenPdfDialog
            // 
            resources.ApplyResources(this._OpenPdfDialog, "_OpenPdfDialog");
            // 
            // statusStrip1
            // 
            this.statusStrip1.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._MainStatusLabel});
            resources.ApplyResources(this.statusStrip1, "statusStrip1");
            this.statusStrip1.Name = "statusStrip1";
            // 
            // _MainStatusLabel
            // 
            this._MainStatusLabel.Name = "_MainStatusLabel";
            resources.ApplyResources(this._MainStatusLabel, "_MainStatusLabel");
            // 
            // _GeneralToolbar
            // 
            this._GeneralToolbar.ImageScalingSize = new System.Drawing.Size(20, 20);
            this._GeneralToolbar.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            _CustomizeToolbar});
            resources.ApplyResources(this._GeneralToolbar, "_GeneralToolbar");
            this._GeneralToolbar.Name = "_GeneralToolbar";
            this._GeneralToolbar.RenderMode = System.Windows.Forms.ToolStripRenderMode.System;
            // 
            // _FunctionContainer
            // 
            this._FunctionContainer.DisplayStyle = TradeWright.UI.Forms.TabStyle.IE8;
            // 
            // 
            // 
            this._FunctionContainer.DisplayStyleProvider.BlendStyle = TradeWright.UI.Forms.BlendStyle.Normal;
            this._FunctionContainer.DisplayStyleProvider.BorderColorDisabled = System.Drawing.SystemColors.ControlLight;
            this._FunctionContainer.DisplayStyleProvider.BorderColorFocused = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185)))));
            this._FunctionContainer.DisplayStyleProvider.BorderColorHighlighted = System.Drawing.SystemColors.ControlDark;
            this._FunctionContainer.DisplayStyleProvider.BorderColorSelected = System.Drawing.SystemColors.ControlDark;
            this._FunctionContainer.DisplayStyleProvider.BorderColorUnselected = System.Drawing.SystemColors.ControlDark;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonFillColorFocused = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonFillColorFocusedActive = System.Drawing.Color.White;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonFillColorHighlighted = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonFillColorHighlightedActive = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonFillColorSelected = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonFillColorSelectedActive = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonFillColorUnselected = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonOutlineColorFocused = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonOutlineColorFocusedActive = System.Drawing.SystemColors.ControlDark;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonOutlineColorHighlighted = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonOutlineColorHighlightedActive = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonOutlineColorSelected = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonOutlineColorSelectedActive = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserButtonOutlineColorUnselected = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.CloserColorFocused = System.Drawing.Color.Black;
            this._FunctionContainer.DisplayStyleProvider.CloserColorFocusedActive = System.Drawing.Color.Red;
            this._FunctionContainer.DisplayStyleProvider.CloserColorHighlighted = System.Drawing.Color.Black;
            this._FunctionContainer.DisplayStyleProvider.CloserColorHighlightedActive = System.Drawing.SystemColors.ControlDark;
            this._FunctionContainer.DisplayStyleProvider.CloserColorSelected = System.Drawing.Color.Black;
            this._FunctionContainer.DisplayStyleProvider.CloserColorSelectedActive = System.Drawing.SystemColors.ControlDark;
            this._FunctionContainer.DisplayStyleProvider.CloserColorUnselected = System.Drawing.Color.Empty;
            this._FunctionContainer.DisplayStyleProvider.FocusTrack = false;
            this._FunctionContainer.DisplayStyleProvider.HotTrack = true;
            this._FunctionContainer.DisplayStyleProvider.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this._FunctionContainer.DisplayStyleProvider.Opacity = 1F;
            this._FunctionContainer.DisplayStyleProvider.Overlap = 0;
            this._FunctionContainer.DisplayStyleProvider.Padding = new System.Drawing.Point(6, 5);
            this._FunctionContainer.DisplayStyleProvider.PageBackgroundColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.PageBackgroundColorFocused = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.PageBackgroundColorHighlighted = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.PageBackgroundColorSelected = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.PageBackgroundColorUnselected = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(223)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.Radius = 3;
            this._FunctionContainer.DisplayStyleProvider.SelectedTabIsLarger = true;
            this._FunctionContainer.DisplayStyleProvider.ShowTabCloser = true;
            this._FunctionContainer.DisplayStyleProvider.TabColorDisabled1 = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorDisabled2 = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorFocused1 = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorFocused2 = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(223)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorHighLighted1 = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(244)))), ((int)(((byte)(252)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorHighLighted2 = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(223)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorSelected1 = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorSelected2 = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(223)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorUnSelected1 = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(223)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabColorUnSelected2 = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(223)))), ((int)(((byte)(255)))));
            this._FunctionContainer.DisplayStyleProvider.TabPageMargin = new System.Windows.Forms.Padding(0, 4, 0, 4);
            this._FunctionContainer.DisplayStyleProvider.TextColorDisabled = System.Drawing.SystemColors.ControlDark;
            this._FunctionContainer.DisplayStyleProvider.TextColorFocused = System.Drawing.SystemColors.ControlText;
            this._FunctionContainer.DisplayStyleProvider.TextColorHighlighted = System.Drawing.SystemColors.ControlText;
            this._FunctionContainer.DisplayStyleProvider.TextColorSelected = System.Drawing.SystemColors.ControlText;
            this._FunctionContainer.DisplayStyleProvider.TextColorUnselected = System.Drawing.SystemColors.ControlText;
            resources.ApplyResources(this._FunctionContainer, "_FunctionContainer");
            this._FunctionContainer.DrawMode = System.Windows.Forms.TabDrawMode.OwnerDrawFixed;
            this._FunctionContainer.HotTrack = true;
            this._FunctionContainer.Name = "_FunctionContainer";
            this._FunctionContainer.SelectedIndex = 0;
            this._FunctionContainer.TabCloserButtonSize = 18;
            // 
            // MainForm
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._FunctionContainer);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this._GeneralToolbar);
            this.Controls.Add(this._MainMenu);
            this.MainMenuStrip = this._MainMenu;
            this.Name = "MainForm";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.MainForm_FormClosed);
            this._MainMenu.ResumeLayout(false);
            this._MainMenu.PerformLayout();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this._GeneralToolbar.ResumeLayout(false);
            this._GeneralToolbar.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ToolTip _ToolTip;
        private System.Windows.Forms.SaveFileDialog _SaveConfigDialog;
        private System.Windows.Forms.OpenFileDialog _OpenConfigDialog;
        private System.Windows.Forms.MenuStrip _MainMenu;
        private System.Windows.Forms.ToolStripMenuItem _File;
        private System.Windows.Forms.ToolStripMenuItem _RecentFiles;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator14;
        private System.Windows.Forms.OpenFileDialog _OpenPdfDialog;
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripMenuItem _ResetOptions;
        private System.Windows.Forms.ToolStrip _GeneralToolbar;
        private TradeWright.UI.Forms.TabControlExtra _FunctionContainer;
        private System.Windows.Forms.ToolStripStatusLabel _MainStatusLabel;
    }
}

