namespace PDFPatcher.Functions
{
	partial class MergerOptionForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MergerOptionForm));
            this._MainTab = new System.Windows.Forms.TabControl();
            this._FilePage = new System.Windows.Forms.TabPage();
            this._CajSortBox = new System.Windows.Forms.CheckBox();
            this._NumericAwareSortBox = new System.Windows.Forms.CheckBox();
            this._SubFoldersBeforeFilesBox = new System.Windows.Forms.CheckBox();
            this._AutoBookmarkTitleBox = new System.Windows.Forms.CheckBox();
            this._IgnoreLeadingNumbersBox = new System.Windows.Forms.CheckBox();
            this._RemoveOrphanBoomarksBox = new System.Windows.Forms.CheckBox();
            this._KeepSourcePdfBookmarkBox = new System.Windows.Forms.CheckBox();
            this._LayoutPage = new System.Windows.Forms.TabPage();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this._RecompressImageBox = new System.Windows.Forms.CheckBox();
            this._AutoMaskBWImageBox = new System.Windows.Forms.CheckBox();
            this._ImageGroupBox = new System.Windows.Forms.GroupBox();
            this._AutoScaleDownBox = new System.Windows.Forms.CheckBox();
            this._AutoScaleUpBox = new System.Windows.Forms.CheckBox();
            this._LayoutGroupBox = new System.Windows.Forms.GroupBox();
            this._RotationBox = new System.Windows.Forms.ComboBox();
            this._SourceOrientationBox = new System.Windows.Forms.ComboBox();
            this._UnifyOrientationBox = new System.Windows.Forms.CheckBox();
            this._HeightBox = new System.Windows.Forms.NumericUpDown();
            this._WidthBox = new System.Windows.Forms.NumericUpDown();
            this._ImageVAlignBox = new System.Windows.Forms.ComboBox();
            this._ImageHAlignBox = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this._PageSizeBox = new System.Windows.Forms.ComboBox();
            this._AutoRotateBox = new System.Windows.Forms.CheckBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this._MarginGroupBox = new System.Windows.Forms.GroupBox();
            this._SyncMarginsBox = new System.Windows.Forms.CheckBox();
            this._RightMarginBox = new System.Windows.Forms.NumericUpDown();
            this._LeftMarginBox = new System.Windows.Forms.NumericUpDown();
            this._BottomMarginBox = new System.Windows.Forms.NumericUpDown();
            this._TopMarginBox = new System.Windows.Forms.NumericUpDown();
            this.label7 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this._PdfGroupBox = new System.Windows.Forms.GroupBox();
            this._ResizePdfPagesBox = new System.Windows.Forms.RadioButton();
            this._ScalePdfPagesBox = new System.Windows.Forms.RadioButton();
            this._ViewerSettingsPage = new System.Windows.Forms.TabPage();
            this._ViewerSettingsEditor = new PDFPatcher.Functions.ViewerPreferenceEditor();
            this._DocumentInfoPage = new System.Windows.Forms.TabPage();
            this._FullCompressionBox = new System.Windows.Forms.CheckBox();
            this._DocumentInfoEditor = new PDFPatcher.Functions.DocumentInfoEditor();
            this._PageLabelsPage = new System.Windows.Forms.TabPage();
            this._PageLabelEditor = new PDFPatcher.Functions.PageLabelEditor();
            this._MainTab.SuspendLayout();
            this._FilePage.SuspendLayout();
            this._LayoutPage.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this._ImageGroupBox.SuspendLayout();
            this._LayoutGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._HeightBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._WidthBox)).BeginInit();
            this._MarginGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._RightMarginBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._LeftMarginBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._BottomMarginBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._TopMarginBox)).BeginInit();
            this._PdfGroupBox.SuspendLayout();
            this._ViewerSettingsPage.SuspendLayout();
            this._DocumentInfoPage.SuspendLayout();
            this._PageLabelsPage.SuspendLayout();
            this.SuspendLayout();
            // 
            // _MainTab
            // 
            resources.ApplyResources(this._MainTab, "_MainTab");
            this._MainTab.Controls.Add(this._FilePage);
            this._MainTab.Controls.Add(this._LayoutPage);
            this._MainTab.Controls.Add(this._ViewerSettingsPage);
            this._MainTab.Controls.Add(this._DocumentInfoPage);
            this._MainTab.Controls.Add(this._PageLabelsPage);
            this._MainTab.Name = "_MainTab";
            this._MainTab.SelectedIndex = 0;
            // 
            // _FilePage
            // 
            this._FilePage.Controls.Add(this._CajSortBox);
            this._FilePage.Controls.Add(this._NumericAwareSortBox);
            this._FilePage.Controls.Add(this._SubFoldersBeforeFilesBox);
            this._FilePage.Controls.Add(this._AutoBookmarkTitleBox);
            this._FilePage.Controls.Add(this._IgnoreLeadingNumbersBox);
            this._FilePage.Controls.Add(this._RemoveOrphanBoomarksBox);
            this._FilePage.Controls.Add(this._KeepSourcePdfBookmarkBox);
            resources.ApplyResources(this._FilePage, "_FilePage");
            this._FilePage.Name = "_FilePage";
            this._FilePage.UseVisualStyleBackColor = true;
            // 
            // _CajSortBox
            // 
            resources.ApplyResources(this._CajSortBox, "_CajSortBox");
            this._CajSortBox.Name = "_CajSortBox";
            this._CajSortBox.UseVisualStyleBackColor = true;
            // 
            // _NumericAwareSortBox
            // 
            resources.ApplyResources(this._NumericAwareSortBox, "_NumericAwareSortBox");
            this._NumericAwareSortBox.Name = "_NumericAwareSortBox";
            this._NumericAwareSortBox.UseVisualStyleBackColor = true;
            // 
            // _SubFoldersBeforeFilesBox
            // 
            resources.ApplyResources(this._SubFoldersBeforeFilesBox, "_SubFoldersBeforeFilesBox");
            this._SubFoldersBeforeFilesBox.Name = "_SubFoldersBeforeFilesBox";
            this._SubFoldersBeforeFilesBox.UseVisualStyleBackColor = true;
            // 
            // _AutoBookmarkTitleBox
            // 
            resources.ApplyResources(this._AutoBookmarkTitleBox, "_AutoBookmarkTitleBox");
            this._AutoBookmarkTitleBox.Name = "_AutoBookmarkTitleBox";
            this._AutoBookmarkTitleBox.UseVisualStyleBackColor = true;
            // 
            // _IgnoreLeadingNumbersBox
            // 
            resources.ApplyResources(this._IgnoreLeadingNumbersBox, "_IgnoreLeadingNumbersBox");
            this._IgnoreLeadingNumbersBox.Name = "_IgnoreLeadingNumbersBox";
            this._IgnoreLeadingNumbersBox.UseVisualStyleBackColor = true;
            // 
            // _RemoveOrphanBoomarksBox
            // 
            resources.ApplyResources(this._RemoveOrphanBoomarksBox, "_RemoveOrphanBoomarksBox");
            this._RemoveOrphanBoomarksBox.Name = "_RemoveOrphanBoomarksBox";
            this._RemoveOrphanBoomarksBox.UseVisualStyleBackColor = true;
            // 
            // _KeepSourcePdfBookmarkBox
            // 
            resources.ApplyResources(this._KeepSourcePdfBookmarkBox, "_KeepSourcePdfBookmarkBox");
            this._KeepSourcePdfBookmarkBox.Name = "_KeepSourcePdfBookmarkBox";
            this._KeepSourcePdfBookmarkBox.UseVisualStyleBackColor = true;
            // 
            // _LayoutPage
            // 
            this._LayoutPage.Controls.Add(this.groupBox2);
            this._LayoutPage.Controls.Add(this._ImageGroupBox);
            this._LayoutPage.Controls.Add(this._LayoutGroupBox);
            this._LayoutPage.Controls.Add(this._MarginGroupBox);
            this._LayoutPage.Controls.Add(this._PdfGroupBox);
            resources.ApplyResources(this._LayoutPage, "_LayoutPage");
            this._LayoutPage.Name = "_LayoutPage";
            this._LayoutPage.UseVisualStyleBackColor = true;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this._RecompressImageBox);
            this.groupBox2.Controls.Add(this._AutoMaskBWImageBox);
            resources.ApplyResources(this.groupBox2, "groupBox2");
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.TabStop = false;
            // 
            // _RecompressImageBox
            // 
            resources.ApplyResources(this._RecompressImageBox, "_RecompressImageBox");
            this._RecompressImageBox.Name = "_RecompressImageBox";
            this._RecompressImageBox.UseVisualStyleBackColor = true;
            // 
            // _AutoMaskBWImageBox
            // 
            resources.ApplyResources(this._AutoMaskBWImageBox, "_AutoMaskBWImageBox");
            this._AutoMaskBWImageBox.Name = "_AutoMaskBWImageBox";
            this._AutoMaskBWImageBox.UseVisualStyleBackColor = true;
            // 
            // _ImageGroupBox
            // 
            this._ImageGroupBox.Controls.Add(this._AutoScaleDownBox);
            this._ImageGroupBox.Controls.Add(this._AutoScaleUpBox);
            resources.ApplyResources(this._ImageGroupBox, "_ImageGroupBox");
            this._ImageGroupBox.Name = "_ImageGroupBox";
            this._ImageGroupBox.TabStop = false;
            // 
            // _AutoScaleDownBox
            // 
            resources.ApplyResources(this._AutoScaleDownBox, "_AutoScaleDownBox");
            this._AutoScaleDownBox.Checked = true;
            this._AutoScaleDownBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this._AutoScaleDownBox.Name = "_AutoScaleDownBox";
            this._AutoScaleDownBox.UseVisualStyleBackColor = true;
            // 
            // _AutoScaleUpBox
            // 
            resources.ApplyResources(this._AutoScaleUpBox, "_AutoScaleUpBox");
            this._AutoScaleUpBox.Name = "_AutoScaleUpBox";
            this._AutoScaleUpBox.UseVisualStyleBackColor = true;
            // 
            // _LayoutGroupBox
            // 
            this._LayoutGroupBox.Controls.Add(this._RotationBox);
            this._LayoutGroupBox.Controls.Add(this._SourceOrientationBox);
            this._LayoutGroupBox.Controls.Add(this._UnifyOrientationBox);
            this._LayoutGroupBox.Controls.Add(this._HeightBox);
            this._LayoutGroupBox.Controls.Add(this._WidthBox);
            this._LayoutGroupBox.Controls.Add(this._ImageVAlignBox);
            this._LayoutGroupBox.Controls.Add(this._ImageHAlignBox);
            this._LayoutGroupBox.Controls.Add(this.label2);
            this._LayoutGroupBox.Controls.Add(this.label8);
            this._LayoutGroupBox.Controls.Add(this._PageSizeBox);
            this._LayoutGroupBox.Controls.Add(this._AutoRotateBox);
            this._LayoutGroupBox.Controls.Add(this.label5);
            this._LayoutGroupBox.Controls.Add(this.label4);
            resources.ApplyResources(this._LayoutGroupBox, "_LayoutGroupBox");
            this._LayoutGroupBox.Name = "_LayoutGroupBox";
            this._LayoutGroupBox.TabStop = false;
            // 
            // _RotationBox
            // 
            this._RotationBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._RotationBox.FormattingEnabled = true;
            this._RotationBox.Items.AddRange(new object[] {
            resources.GetString("_RotationBox.Items"),
            resources.GetString("_RotationBox.Items1")});
            resources.ApplyResources(this._RotationBox, "_RotationBox");
            this._RotationBox.Name = "_RotationBox";
            // 
            // _SourceOrientationBox
            // 
            this._SourceOrientationBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._SourceOrientationBox.FormattingEnabled = true;
            this._SourceOrientationBox.Items.AddRange(new object[] {
            resources.GetString("_SourceOrientationBox.Items"),
            resources.GetString("_SourceOrientationBox.Items1")});
            resources.ApplyResources(this._SourceOrientationBox, "_SourceOrientationBox");
            this._SourceOrientationBox.Name = "_SourceOrientationBox";
            // 
            // _UnifyOrientationBox
            // 
            resources.ApplyResources(this._UnifyOrientationBox, "_UnifyOrientationBox");
            this._UnifyOrientationBox.Name = "_UnifyOrientationBox";
            this._UnifyOrientationBox.UseVisualStyleBackColor = true;
            // 
            // _HeightBox
            // 
            this._HeightBox.DecimalPlaces = 2;
            this._HeightBox.Increment = new decimal(new int[] {
            1,
            0,
            0,
            131072});
            resources.ApplyResources(this._HeightBox, "_HeightBox");
            this._HeightBox.Maximum = new decimal(new int[] {
            9999,
            0,
            0,
            0});
            this._HeightBox.Name = "_HeightBox";
            // 
            // _WidthBox
            // 
            this._WidthBox.DecimalPlaces = 2;
            this._WidthBox.Increment = new decimal(new int[] {
            1,
            0,
            0,
            131072});
            resources.ApplyResources(this._WidthBox, "_WidthBox");
            this._WidthBox.Maximum = new decimal(new int[] {
            9999,
            0,
            0,
            0});
            this._WidthBox.Name = "_WidthBox";
            // 
            // _ImageVAlignBox
            // 
            this._ImageVAlignBox.DisplayMember = "Key";
            this._ImageVAlignBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this._ImageVAlignBox, "_ImageVAlignBox");
            this._ImageVAlignBox.Name = "_ImageVAlignBox";
            this._ImageVAlignBox.ValueMember = "Value";
            // 
            // _ImageHAlignBox
            // 
            this._ImageHAlignBox.DisplayMember = "Key";
            this._ImageHAlignBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this._ImageHAlignBox, "_ImageHAlignBox");
            this._ImageHAlignBox.Name = "_ImageHAlignBox";
            this._ImageHAlignBox.ValueMember = "Value";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // label8
            // 
            resources.ApplyResources(this.label8, "label8");
            this.label8.Name = "label8";
            // 
            // _PageSizeBox
            // 
            this._PageSizeBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this._PageSizeBox, "_PageSizeBox");
            this._PageSizeBox.Name = "_PageSizeBox";
            this._PageSizeBox.SelectedIndexChanged += new System.EventHandler(this._PageSizeBox_SelectedIndexChanged);
            // 
            // _AutoRotateBox
            // 
            resources.ApplyResources(this._AutoRotateBox, "_AutoRotateBox");
            this._AutoRotateBox.Checked = true;
            this._AutoRotateBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this._AutoRotateBox.Name = "_AutoRotateBox";
            this._AutoRotateBox.UseVisualStyleBackColor = true;
            // 
            // label5
            // 
            resources.ApplyResources(this.label5, "label5");
            this.label5.Name = "label5";
            // 
            // label4
            // 
            resources.ApplyResources(this.label4, "label4");
            this.label4.Name = "label4";
            // 
            // _MarginGroupBox
            // 
            this._MarginGroupBox.Controls.Add(this._SyncMarginsBox);
            this._MarginGroupBox.Controls.Add(this._RightMarginBox);
            this._MarginGroupBox.Controls.Add(this._LeftMarginBox);
            this._MarginGroupBox.Controls.Add(this._BottomMarginBox);
            this._MarginGroupBox.Controls.Add(this._TopMarginBox);
            this._MarginGroupBox.Controls.Add(this.label7);
            this._MarginGroupBox.Controls.Add(this.label3);
            this._MarginGroupBox.Controls.Add(this.label6);
            this._MarginGroupBox.Controls.Add(this.label1);
            resources.ApplyResources(this._MarginGroupBox, "_MarginGroupBox");
            this._MarginGroupBox.Name = "_MarginGroupBox";
            this._MarginGroupBox.TabStop = false;
            // 
            // _SyncMarginsBox
            // 
            resources.ApplyResources(this._SyncMarginsBox, "_SyncMarginsBox");
            this._SyncMarginsBox.Checked = true;
            this._SyncMarginsBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this._SyncMarginsBox.Name = "_SyncMarginsBox";
            this._SyncMarginsBox.UseVisualStyleBackColor = true;
            // 
            // _RightMarginBox
            // 
            this._RightMarginBox.DecimalPlaces = 2;
            this._RightMarginBox.Increment = new decimal(new int[] {
            1,
            0,
            0,
            131072});
            resources.ApplyResources(this._RightMarginBox, "_RightMarginBox");
            this._RightMarginBox.Maximum = new decimal(new int[] {
            99,
            0,
            0,
            0});
            this._RightMarginBox.Name = "_RightMarginBox";
            this._RightMarginBox.ValueChanged += new System.EventHandler(this.MarginBox_ValueChanged);
            // 
            // _LeftMarginBox
            // 
            this._LeftMarginBox.DecimalPlaces = 2;
            this._LeftMarginBox.Increment = new decimal(new int[] {
            1,
            0,
            0,
            131072});
            resources.ApplyResources(this._LeftMarginBox, "_LeftMarginBox");
            this._LeftMarginBox.Maximum = new decimal(new int[] {
            99,
            0,
            0,
            0});
            this._LeftMarginBox.Name = "_LeftMarginBox";
            this._LeftMarginBox.ValueChanged += new System.EventHandler(this.MarginBox_ValueChanged);
            // 
            // _BottomMarginBox
            // 
            this._BottomMarginBox.DecimalPlaces = 2;
            this._BottomMarginBox.Increment = new decimal(new int[] {
            1,
            0,
            0,
            131072});
            resources.ApplyResources(this._BottomMarginBox, "_BottomMarginBox");
            this._BottomMarginBox.Maximum = new decimal(new int[] {
            99,
            0,
            0,
            0});
            this._BottomMarginBox.Name = "_BottomMarginBox";
            this._BottomMarginBox.ValueChanged += new System.EventHandler(this.MarginBox_ValueChanged);
            // 
            // _TopMarginBox
            // 
            this._TopMarginBox.DecimalPlaces = 2;
            this._TopMarginBox.Increment = new decimal(new int[] {
            1,
            0,
            0,
            131072});
            resources.ApplyResources(this._TopMarginBox, "_TopMarginBox");
            this._TopMarginBox.Maximum = new decimal(new int[] {
            99,
            0,
            0,
            0});
            this._TopMarginBox.Name = "_TopMarginBox";
            this._TopMarginBox.ValueChanged += new System.EventHandler(this.MarginBox_ValueChanged);
            // 
            // label7
            // 
            resources.ApplyResources(this.label7, "label7");
            this.label7.Name = "label7";
            // 
            // label3
            // 
            resources.ApplyResources(this.label3, "label3");
            this.label3.Name = "label3";
            // 
            // label6
            // 
            resources.ApplyResources(this.label6, "label6");
            this.label6.Name = "label6";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // _PdfGroupBox
            // 
            this._PdfGroupBox.Controls.Add(this._ResizePdfPagesBox);
            this._PdfGroupBox.Controls.Add(this._ScalePdfPagesBox);
            resources.ApplyResources(this._PdfGroupBox, "_PdfGroupBox");
            this._PdfGroupBox.Name = "_PdfGroupBox";
            this._PdfGroupBox.TabStop = false;
            // 
            // _ResizePdfPagesBox
            // 
            resources.ApplyResources(this._ResizePdfPagesBox, "_ResizePdfPagesBox");
            this._ResizePdfPagesBox.Name = "_ResizePdfPagesBox";
            this._ResizePdfPagesBox.UseVisualStyleBackColor = true;
            // 
            // _ScalePdfPagesBox
            // 
            resources.ApplyResources(this._ScalePdfPagesBox, "_ScalePdfPagesBox");
            this._ScalePdfPagesBox.Name = "_ScalePdfPagesBox";
            this._ScalePdfPagesBox.TabStop = true;
            this._ScalePdfPagesBox.UseVisualStyleBackColor = true;
            // 
            // _ViewerSettingsPage
            // 
            this._ViewerSettingsPage.Controls.Add(this._ViewerSettingsEditor);
            resources.ApplyResources(this._ViewerSettingsPage, "_ViewerSettingsPage");
            this._ViewerSettingsPage.Name = "_ViewerSettingsPage";
            this._ViewerSettingsPage.UseVisualStyleBackColor = true;
            // 
            // _ViewerSettingsEditor
            // 
            resources.ApplyResources(this._ViewerSettingsEditor, "_ViewerSettingsEditor");
            this._ViewerSettingsEditor.Name = "_ViewerSettingsEditor";
            // 
            // _DocumentInfoPage
            // 
            this._DocumentInfoPage.Controls.Add(this._FullCompressionBox);
            this._DocumentInfoPage.Controls.Add(this._DocumentInfoEditor);
            resources.ApplyResources(this._DocumentInfoPage, "_DocumentInfoPage");
            this._DocumentInfoPage.Name = "_DocumentInfoPage";
            this._DocumentInfoPage.UseVisualStyleBackColor = true;
            // 
            // _FullCompressionBox
            // 
            resources.ApplyResources(this._FullCompressionBox, "_FullCompressionBox");
            this._FullCompressionBox.Name = "_FullCompressionBox";
            this._FullCompressionBox.UseVisualStyleBackColor = true;
            // 
            // _DocumentInfoEditor
            // 
            resources.ApplyResources(this._DocumentInfoEditor, "_DocumentInfoEditor");
            this._DocumentInfoEditor.Name = "_DocumentInfoEditor";
            // 
            // _PageLabelsPage
            // 
            this._PageLabelsPage.Controls.Add(this._PageLabelEditor);
            resources.ApplyResources(this._PageLabelsPage, "_PageLabelsPage");
            this._PageLabelsPage.Name = "_PageLabelsPage";
            this._PageLabelsPage.UseVisualStyleBackColor = true;
            // 
            // _PageLabelEditor
            // 
            resources.ApplyResources(this._PageLabelEditor, "_PageLabelEditor");
            this._PageLabelEditor.Labels = null;
            this._PageLabelEditor.Name = "_PageLabelEditor";
            // 
            // MergerOptionForm
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._MainTab);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "MergerOptionForm";
            this.ShowInTaskbar = false;
            this._MainTab.ResumeLayout(false);
            this._FilePage.ResumeLayout(false);
            this._FilePage.PerformLayout();
            this._LayoutPage.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this._ImageGroupBox.ResumeLayout(false);
            this._ImageGroupBox.PerformLayout();
            this._LayoutGroupBox.ResumeLayout(false);
            this._LayoutGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this._HeightBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._WidthBox)).EndInit();
            this._MarginGroupBox.ResumeLayout(false);
            this._MarginGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this._RightMarginBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._LeftMarginBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._BottomMarginBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._TopMarginBox)).EndInit();
            this._PdfGroupBox.ResumeLayout(false);
            this._PdfGroupBox.PerformLayout();
            this._ViewerSettingsPage.ResumeLayout(false);
            this._DocumentInfoPage.ResumeLayout(false);
            this._DocumentInfoPage.PerformLayout();
            this._PageLabelsPage.ResumeLayout(false);
            this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.TabControl _MainTab;
		private System.Windows.Forms.TabPage _LayoutPage;
		private System.Windows.Forms.TabPage _FilePage;
		private System.Windows.Forms.GroupBox groupBox2;
		private System.Windows.Forms.CheckBox _AutoMaskBWImageBox;
		private System.Windows.Forms.GroupBox _ImageGroupBox;
		private System.Windows.Forms.CheckBox _AutoScaleDownBox;
		private System.Windows.Forms.CheckBox _AutoScaleUpBox;
		private System.Windows.Forms.GroupBox _LayoutGroupBox;
		private System.Windows.Forms.NumericUpDown _HeightBox;
		private System.Windows.Forms.NumericUpDown _WidthBox;
		private System.Windows.Forms.ComboBox _ImageVAlignBox;
		private System.Windows.Forms.ComboBox _ImageHAlignBox;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.Label label8;
		private System.Windows.Forms.ComboBox _PageSizeBox;
		private System.Windows.Forms.CheckBox _AutoRotateBox;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.GroupBox _MarginGroupBox;
		private System.Windows.Forms.CheckBox _SyncMarginsBox;
		private System.Windows.Forms.NumericUpDown _RightMarginBox;
		private System.Windows.Forms.NumericUpDown _LeftMarginBox;
		private System.Windows.Forms.NumericUpDown _BottomMarginBox;
		private System.Windows.Forms.NumericUpDown _TopMarginBox;
		private System.Windows.Forms.Label label7;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.GroupBox _PdfGroupBox;
		private System.Windows.Forms.RadioButton _ResizePdfPagesBox;
		private System.Windows.Forms.RadioButton _ScalePdfPagesBox;
		private System.Windows.Forms.CheckBox _IgnoreLeadingNumbersBox;
		private System.Windows.Forms.TabPage _ViewerSettingsPage;
		private ViewerPreferenceEditor _ViewerSettingsEditor;
		private System.Windows.Forms.TabPage _DocumentInfoPage;
		private DocumentInfoEditor _DocumentInfoEditor;
		private System.Windows.Forms.TabPage _PageLabelsPage;
		private PageLabelEditor _PageLabelEditor;
		private System.Windows.Forms.CheckBox _RecompressImageBox;
		private System.Windows.Forms.CheckBox _FullCompressionBox;
		private System.Windows.Forms.CheckBox _AutoBookmarkTitleBox;
		private System.Windows.Forms.CheckBox _SubFoldersBeforeFilesBox;
		private System.Windows.Forms.CheckBox _NumericAwareSortBox;
		private System.Windows.Forms.CheckBox _RemoveOrphanBoomarksBox;
		private System.Windows.Forms.CheckBox _KeepSourcePdfBookmarkBox;
		private System.Windows.Forms.CheckBox _CajSortBox;
		private System.Windows.Forms.CheckBox _UnifyOrientationBox;
		private System.Windows.Forms.ComboBox _RotationBox;
		private System.Windows.Forms.ComboBox _SourceOrientationBox;
	}
}
