namespace PDFPatcher.Functions
{
	partial class RenamePreviewForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RenamePreviewForm));
            this._RenamePreviewBox = new System.Windows.Forms.ListView();
            this._OriginalNameColumn = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this._OutputNameColumn = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this._OriginalFolderColumn = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this._OutputFolderColumn = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.label1 = new System.Windows.Forms.Label();
            this._OKButton = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // _RenamePreviewBox
            // 
            resources.ApplyResources(this._RenamePreviewBox, "_RenamePreviewBox");
            this._RenamePreviewBox.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this._OriginalNameColumn,
            this._OutputNameColumn,
            this._OriginalFolderColumn,
            this._OutputFolderColumn});
            this._RenamePreviewBox.GridLines = true;
            this._RenamePreviewBox.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
            this._RenamePreviewBox.HideSelection = false;
            this._RenamePreviewBox.Name = "_RenamePreviewBox";
            this._RenamePreviewBox.UseCompatibleStateImageBehavior = false;
            this._RenamePreviewBox.View = System.Windows.Forms.View.Details;
            // 
            // _OriginalNameColumn
            // 
            resources.ApplyResources(this._OriginalNameColumn, "_OriginalNameColumn");
            // 
            // _OutputNameColumn
            // 
            resources.ApplyResources(this._OutputNameColumn, "_OutputNameColumn");
            // 
            // _OriginalFolderColumn
            // 
            resources.ApplyResources(this._OriginalFolderColumn, "_OriginalFolderColumn");
            // 
            // _OutputFolderColumn
            // 
            resources.ApplyResources(this._OutputFolderColumn, "_OutputFolderColumn");
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // _OKButton
            // 
            resources.ApplyResources(this._OKButton, "_OKButton");
            this._OKButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._OKButton.Name = "_OKButton";
            this._OKButton.UseVisualStyleBackColor = true;
            this._OKButton.Click += new System.EventHandler(this._OKButton_Click);
            // 
            // RenamePreviewForm
            // 
            this.AcceptButton = this._OKButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._OKButton;
            this.Controls.Add(this._OKButton);
            this.Controls.Add(this.label1);
            this.Controls.Add(this._RenamePreviewBox);
            this.Name = "RenamePreviewForm";
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.ListView _RenamePreviewBox;
		private System.Windows.Forms.ColumnHeader _OriginalNameColumn;
		private System.Windows.Forms.ColumnHeader _OutputNameColumn;
		private System.Windows.Forms.ColumnHeader _OriginalFolderColumn;
		private System.Windows.Forms.ColumnHeader _OutputFolderColumn;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.Button _OKButton;
	}
}
