namespace PDFPatcher.Functions
{
	partial class SourcePdfOptionForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SourcePdfOptionForm));
            this._OkButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this._MessageLabel = new System.Windows.Forms.Label();
            this._PageRangeBox = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this._SourceFileBox = new System.Windows.Forms.TextBox();
            this._ImportImagesOnlyBox = new System.Windows.Forms.CheckBox();
            this._ExtractImageOptionBox = new System.Windows.Forms.GroupBox();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this._MinCropWidthBox = new System.Windows.Forms.NumericUpDown();
            this._MinCropHeightBox = new System.Windows.Forms.NumericUpDown();
            this._MinWidthBox = new System.Windows.Forms.NumericUpDown();
            this._MinHeightBox = new System.Windows.Forms.NumericUpDown();
            this._VerticalFlipImagesBox = new System.Windows.Forms.CheckBox();
            this._InvertBlackAndWhiteImageBox = new System.Windows.Forms.CheckBox();
            this._MergeImagesBox = new System.Windows.Forms.CheckBox();
            this.label5 = new System.Windows.Forms.Label();
            this._RightMarginBox = new System.Windows.Forms.NumericUpDown();
            this._LeftMarginBox = new System.Windows.Forms.NumericUpDown();
            this._BottomMarginBox = new System.Windows.Forms.NumericUpDown();
            this._TopMarginBox = new System.Windows.Forms.NumericUpDown();
            this.label7 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this._ExtractImageOptionBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._MinCropWidthBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._MinCropHeightBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._MinWidthBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._MinHeightBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._RightMarginBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._LeftMarginBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._BottomMarginBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._TopMarginBox)).BeginInit();
            this.SuspendLayout();
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // _CancelButton
            // 
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // _MessageLabel
            // 
            resources.ApplyResources(this._MessageLabel, "_MessageLabel");
            this._MessageLabel.Name = "_MessageLabel";
            // 
            // _PageRangeBox
            // 
            resources.ApplyResources(this._PageRangeBox, "_PageRangeBox");
            this._PageRangeBox.Name = "_PageRangeBox";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // _SourceFileBox
            // 
            resources.ApplyResources(this._SourceFileBox, "_SourceFileBox");
            this._SourceFileBox.Name = "_SourceFileBox";
            this._SourceFileBox.ReadOnly = true;
            // 
            // _ImportImagesOnlyBox
            // 
            resources.ApplyResources(this._ImportImagesOnlyBox, "_ImportImagesOnlyBox");
            this._ImportImagesOnlyBox.Name = "_ImportImagesOnlyBox";
            this._ImportImagesOnlyBox.UseVisualStyleBackColor = true;
            this._ImportImagesOnlyBox.CheckedChanged += new System.EventHandler(this._ImportImagesOnlyBox_CheckedChanged);
            // 
            // _ExtractImageOptionBox
            // 
            this._ExtractImageOptionBox.Controls.Add(this.label13);
            this._ExtractImageOptionBox.Controls.Add(this.label12);
            this._ExtractImageOptionBox.Controls.Add(this.label11);
            this._ExtractImageOptionBox.Controls.Add(this.label8);
            this._ExtractImageOptionBox.Controls.Add(this.label9);
            this._ExtractImageOptionBox.Controls.Add(this.label10);
            this._ExtractImageOptionBox.Controls.Add(this._MinCropWidthBox);
            this._ExtractImageOptionBox.Controls.Add(this._MinCropHeightBox);
            this._ExtractImageOptionBox.Controls.Add(this._MinWidthBox);
            this._ExtractImageOptionBox.Controls.Add(this._MinHeightBox);
            this._ExtractImageOptionBox.Controls.Add(this._VerticalFlipImagesBox);
            this._ExtractImageOptionBox.Controls.Add(this._InvertBlackAndWhiteImageBox);
            this._ExtractImageOptionBox.Controls.Add(this._MergeImagesBox);
            this._ExtractImageOptionBox.Controls.Add(this.label5);
            this._ExtractImageOptionBox.Controls.Add(this._RightMarginBox);
            this._ExtractImageOptionBox.Controls.Add(this._LeftMarginBox);
            this._ExtractImageOptionBox.Controls.Add(this._BottomMarginBox);
            this._ExtractImageOptionBox.Controls.Add(this._TopMarginBox);
            this._ExtractImageOptionBox.Controls.Add(this.label7);
            this._ExtractImageOptionBox.Controls.Add(this.label3);
            this._ExtractImageOptionBox.Controls.Add(this.label6);
            this._ExtractImageOptionBox.Controls.Add(this.label4);
            resources.ApplyResources(this._ExtractImageOptionBox, "_ExtractImageOptionBox");
            this._ExtractImageOptionBox.Name = "_ExtractImageOptionBox";
            this._ExtractImageOptionBox.TabStop = false;
            // 
            // label13
            // 
            resources.ApplyResources(this.label13, "label13");
            this.label13.Name = "label13";
            // 
            // label12
            // 
            resources.ApplyResources(this.label12, "label12");
            this.label12.Name = "label12";
            // 
            // label11
            // 
            resources.ApplyResources(this.label11, "label11");
            this.label11.Name = "label11";
            // 
            // label8
            // 
            resources.ApplyResources(this.label8, "label8");
            this.label8.Name = "label8";
            // 
            // label9
            // 
            resources.ApplyResources(this.label9, "label9");
            this.label9.Name = "label9";
            // 
            // label10
            // 
            resources.ApplyResources(this.label10, "label10");
            this.label10.Name = "label10";
            // 
            // _MinCropWidthBox
            // 
            this._MinCropWidthBox.Increment = new decimal(new int[] {
            100,
            0,
            0,
            0});
            resources.ApplyResources(this._MinCropWidthBox, "_MinCropWidthBox");
            this._MinCropWidthBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._MinCropWidthBox.Name = "_MinCropWidthBox";
            // 
            // _MinCropHeightBox
            // 
            this._MinCropHeightBox.Increment = new decimal(new int[] {
            100,
            0,
            0,
            0});
            resources.ApplyResources(this._MinCropHeightBox, "_MinCropHeightBox");
            this._MinCropHeightBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._MinCropHeightBox.Name = "_MinCropHeightBox";
            // 
            // _MinWidthBox
            // 
            this._MinWidthBox.Increment = new decimal(new int[] {
            10,
            0,
            0,
            0});
            resources.ApplyResources(this._MinWidthBox, "_MinWidthBox");
            this._MinWidthBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._MinWidthBox.Name = "_MinWidthBox";
            // 
            // _MinHeightBox
            // 
            this._MinHeightBox.Increment = new decimal(new int[] {
            10,
            0,
            0,
            0});
            resources.ApplyResources(this._MinHeightBox, "_MinHeightBox");
            this._MinHeightBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._MinHeightBox.Name = "_MinHeightBox";
            // 
            // _VerticalFlipImagesBox
            // 
            resources.ApplyResources(this._VerticalFlipImagesBox, "_VerticalFlipImagesBox");
            this._VerticalFlipImagesBox.Name = "_VerticalFlipImagesBox";
            this._VerticalFlipImagesBox.UseVisualStyleBackColor = true;
            // 
            // _InvertBlackAndWhiteImageBox
            // 
            resources.ApplyResources(this._InvertBlackAndWhiteImageBox, "_InvertBlackAndWhiteImageBox");
            this._InvertBlackAndWhiteImageBox.Name = "_InvertBlackAndWhiteImageBox";
            this._InvertBlackAndWhiteImageBox.UseVisualStyleBackColor = true;
            // 
            // _MergeImagesBox
            // 
            resources.ApplyResources(this._MergeImagesBox, "_MergeImagesBox");
            this._MergeImagesBox.Checked = true;
            this._MergeImagesBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this._MergeImagesBox.Name = "_MergeImagesBox";
            this._MergeImagesBox.UseVisualStyleBackColor = true;
            // 
            // label5
            // 
            resources.ApplyResources(this.label5, "label5");
            this.label5.Name = "label5";
            // 
            // _RightMarginBox
            // 
            this._RightMarginBox.Increment = new decimal(new int[] {
            10,
            0,
            0,
            0});
            resources.ApplyResources(this._RightMarginBox, "_RightMarginBox");
            this._RightMarginBox.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this._RightMarginBox.Name = "_RightMarginBox";
            // 
            // _LeftMarginBox
            // 
            this._LeftMarginBox.Increment = new decimal(new int[] {
            10,
            0,
            0,
            0});
            resources.ApplyResources(this._LeftMarginBox, "_LeftMarginBox");
            this._LeftMarginBox.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this._LeftMarginBox.Name = "_LeftMarginBox";
            // 
            // _BottomMarginBox
            // 
            this._BottomMarginBox.Increment = new decimal(new int[] {
            10,
            0,
            0,
            0});
            resources.ApplyResources(this._BottomMarginBox, "_BottomMarginBox");
            this._BottomMarginBox.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this._BottomMarginBox.Name = "_BottomMarginBox";
            // 
            // _TopMarginBox
            // 
            this._TopMarginBox.Increment = new decimal(new int[] {
            10,
            0,
            0,
            0});
            resources.ApplyResources(this._TopMarginBox, "_TopMarginBox");
            this._TopMarginBox.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this._TopMarginBox.Name = "_TopMarginBox";
            // 
            // label7
            // 
            resources.ApplyResources(this.label7, "label7");
            this.label7.Name = "label7";
            // 
            // label3
            // 
            resources.ApplyResources(this.label3, "label3");
            this.label3.Name = "label3";
            // 
            // label6
            // 
            resources.ApplyResources(this.label6, "label6");
            this.label6.Name = "label6";
            // 
            // label4
            // 
            resources.ApplyResources(this.label4, "label4");
            this.label4.Name = "label4";
            // 
            // SourcePdfOptionForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._PageRangeBox);
            this.Controls.Add(this._ImportImagesOnlyBox);
            this.Controls.Add(this._MessageLabel);
            this.Controls.Add(this._ExtractImageOptionBox);
            this.Controls.Add(this._SourceFileBox);
            this.Controls.Add(this.label2);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "SourcePdfOptionForm";
            this._ExtractImageOptionBox.ResumeLayout(false);
            this._ExtractImageOptionBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this._MinCropWidthBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._MinCropHeightBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._MinWidthBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._MinHeightBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._RightMarginBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._LeftMarginBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._BottomMarginBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._TopMarginBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _OkButton;
		private System.Windows.Forms.Button _CancelButton;
		private System.Windows.Forms.Label _MessageLabel;
		private System.Windows.Forms.TextBox _PageRangeBox;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.TextBox _SourceFileBox;
		private System.Windows.Forms.CheckBox _ImportImagesOnlyBox;
		private System.Windows.Forms.GroupBox _ExtractImageOptionBox;
		private System.Windows.Forms.NumericUpDown _RightMarginBox;
		private System.Windows.Forms.NumericUpDown _LeftMarginBox;
		private System.Windows.Forms.NumericUpDown _BottomMarginBox;
		private System.Windows.Forms.NumericUpDown _TopMarginBox;
		private System.Windows.Forms.Label label7;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.CheckBox _MergeImagesBox;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.CheckBox _InvertBlackAndWhiteImageBox;
		private System.Windows.Forms.CheckBox _VerticalFlipImagesBox;
		private System.Windows.Forms.Label label8;
		private System.Windows.Forms.Label label10;
		private System.Windows.Forms.NumericUpDown _MinWidthBox;
		private System.Windows.Forms.NumericUpDown _MinHeightBox;
		private System.Windows.Forms.Label label11;
		private System.Windows.Forms.Label label9;
		private System.Windows.Forms.NumericUpDown _MinCropWidthBox;
		private System.Windows.Forms.NumericUpDown _MinCropHeightBox;
		private System.Windows.Forms.Label label13;
		private System.Windows.Forms.Label label12;
	}
}

