namespace PDFPatcher.Functions
{
	partial class UpdateForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UpdateForm));
            this._InfoBox = new System.Windows.Forms.RichTextBox();
            this._HomePageButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this._DownloadButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this._CheckUpdateIntervalBox = new System.Windows.Forms.ComboBox();
            this.SuspendLayout();
            // 
            // _InfoBox
            // 
            resources.ApplyResources(this._InfoBox, "_InfoBox");
            this._InfoBox.Name = "_InfoBox";
            this._InfoBox.ReadOnly = true;
            // 
            // _HomePageButton
            // 
            this._HomePageButton.Image = global::PDFPatcher.Properties.Resources.HomePage;
            resources.ApplyResources(this._HomePageButton, "_HomePageButton");
            this._HomePageButton.Name = "_HomePageButton";
            this._HomePageButton.UseVisualStyleBackColor = true;
            // 
            // _CancelButton
            // 
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            // 
            // _DownloadButton
            // 
            resources.ApplyResources(this._DownloadButton, "_DownloadButton");
            this._DownloadButton.Image = global::PDFPatcher.Properties.Resources.Save;
            this._DownloadButton.Name = "_DownloadButton";
            this._DownloadButton.UseVisualStyleBackColor = true;
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // _CheckUpdateIntervalBox
            // 
            this._CheckUpdateIntervalBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._CheckUpdateIntervalBox.FormattingEnabled = true;
            this._CheckUpdateIntervalBox.Items.AddRange(new object[] {
            resources.GetString("_CheckUpdateIntervalBox.Items"),
            resources.GetString("_CheckUpdateIntervalBox.Items1"),
            resources.GetString("_CheckUpdateIntervalBox.Items2"),
            resources.GetString("_CheckUpdateIntervalBox.Items3")});
            resources.ApplyResources(this._CheckUpdateIntervalBox, "_CheckUpdateIntervalBox");
            this._CheckUpdateIntervalBox.Name = "_CheckUpdateIntervalBox";
            // 
            // UpdateForm
            // 
            this.AcceptButton = this._HomePageButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._CheckUpdateIntervalBox);
            this.Controls.Add(this.label1);
            this.Controls.Add(this._DownloadButton);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._HomePageButton);
            this.Controls.Add(this._InfoBox);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "UpdateForm";
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.RichTextBox _InfoBox;
		private System.Windows.Forms.Button _HomePageButton;
		private System.Windows.Forms.Button _CancelButton;
		private System.Windows.Forms.Button _DownloadButton;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.ComboBox _CheckUpdateIntervalBox;
	}
}
