namespace PDFPatcher.Functions
{
	partial class ActionEditorForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ActionEditorForm));
            this._OkButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this._DestinationPanel = new System.Windows.Forms.GroupBox();
            this._PathPanel = new System.Windows.Forms.Panel();
            this._PathBox = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this._NewWindowBox = new System.Windows.Forms.CheckBox();
            this._NamedBox = new System.Windows.Forms.TextBox();
            this._GotoNamedDestBox = new System.Windows.Forms.RadioButton();
            this._GotoLocationBox = new System.Windows.Forms.RadioButton();
            this._LocationPanel = new System.Windows.Forms.Panel();
            this.label10 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this._KeepYBox = new System.Windows.Forms.CheckBox();
            this._PageBox = new System.Windows.Forms.NumericUpDown();
            this._KeepXBox = new System.Windows.Forms.CheckBox();
            this.label5 = new System.Windows.Forms.Label();
            this._ZoomRateBox = new System.Windows.Forms.ComboBox();
            this._LeftBox = new System.Windows.Forms.NumericUpDown();
            this.label7 = new System.Windows.Forms.Label();
            this._TopBox = new System.Windows.Forms.NumericUpDown();
            this.label6 = new System.Windows.Forms.Label();
            this._RectanglePanel = new System.Windows.Forms.Panel();
            this.label8 = new System.Windows.Forms.Label();
            this._WidthBox = new System.Windows.Forms.NumericUpDown();
            this.label9 = new System.Windows.Forms.Label();
            this._HeightBox = new System.Windows.Forms.NumericUpDown();
            this._ActionBox = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this._TitleBox = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this._DefaultOpenBox = new System.Windows.Forms.CheckBox();
            this._ScriptBox = new System.Windows.Forms.GroupBox();
            this._ScriptContentBox = new System.Windows.Forms.TextBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this._AttributesBox = new BrightIdeasSoftware.ObjectListView();
            this._AttrNameColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this._AttrValueColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this._DestinationPanel.SuspendLayout();
            this._PathPanel.SuspendLayout();
            this._LocationPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._PageBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._LeftBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._TopBox)).BeginInit();
            this._RectanglePanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._WidthBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._HeightBox)).BeginInit();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this._ScriptBox.SuspendLayout();
            this.tabPage2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._AttributesBox)).BeginInit();
            this.SuspendLayout();
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // _CancelButton
            // 
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // _DestinationPanel
            // 
            resources.ApplyResources(this._DestinationPanel, "_DestinationPanel");
            this._DestinationPanel.Controls.Add(this._PathPanel);
            this._DestinationPanel.Controls.Add(this._NamedBox);
            this._DestinationPanel.Controls.Add(this._GotoNamedDestBox);
            this._DestinationPanel.Controls.Add(this._GotoLocationBox);
            this._DestinationPanel.Controls.Add(this._LocationPanel);
            this._DestinationPanel.Name = "_DestinationPanel";
            this._DestinationPanel.TabStop = false;
            // 
            // _PathPanel
            // 
            resources.ApplyResources(this._PathPanel, "_PathPanel");
            this._PathPanel.Controls.Add(this._PathBox);
            this._PathPanel.Controls.Add(this.label4);
            this._PathPanel.Controls.Add(this._NewWindowBox);
            this._PathPanel.Name = "_PathPanel";
            // 
            // _PathBox
            // 
            resources.ApplyResources(this._PathBox, "_PathBox");
            this._PathBox.Name = "_PathBox";
            // 
            // label4
            // 
            resources.ApplyResources(this.label4, "label4");
            this.label4.Name = "label4";
            // 
            // _NewWindowBox
            // 
            resources.ApplyResources(this._NewWindowBox, "_NewWindowBox");
            this._NewWindowBox.Name = "_NewWindowBox";
            this._NewWindowBox.UseVisualStyleBackColor = true;
            // 
            // _NamedBox
            // 
            resources.ApplyResources(this._NamedBox, "_NamedBox");
            this._NamedBox.Name = "_NamedBox";
            // 
            // _GotoNamedDestBox
            // 
            resources.ApplyResources(this._GotoNamedDestBox, "_GotoNamedDestBox");
            this._GotoNamedDestBox.Name = "_GotoNamedDestBox";
            this._GotoNamedDestBox.TabStop = true;
            this._GotoNamedDestBox.UseVisualStyleBackColor = true;
            this._GotoNamedDestBox.CheckedChanged += new System.EventHandler(this.Control_ValueChanged);
            // 
            // _GotoLocationBox
            // 
            resources.ApplyResources(this._GotoLocationBox, "_GotoLocationBox");
            this._GotoLocationBox.Name = "_GotoLocationBox";
            this._GotoLocationBox.TabStop = true;
            this._GotoLocationBox.UseVisualStyleBackColor = true;
            this._GotoLocationBox.CheckedChanged += new System.EventHandler(this.Control_ValueChanged);
            // 
            // _LocationPanel
            // 
            resources.ApplyResources(this._LocationPanel, "_LocationPanel");
            this._LocationPanel.Controls.Add(this.label10);
            this._LocationPanel.Controls.Add(this.label3);
            this._LocationPanel.Controls.Add(this._KeepYBox);
            this._LocationPanel.Controls.Add(this._PageBox);
            this._LocationPanel.Controls.Add(this._KeepXBox);
            this._LocationPanel.Controls.Add(this.label5);
            this._LocationPanel.Controls.Add(this._ZoomRateBox);
            this._LocationPanel.Controls.Add(this._LeftBox);
            this._LocationPanel.Controls.Add(this.label7);
            this._LocationPanel.Controls.Add(this._TopBox);
            this._LocationPanel.Controls.Add(this.label6);
            this._LocationPanel.Controls.Add(this._RectanglePanel);
            this._LocationPanel.Name = "_LocationPanel";
            // 
            // label10
            // 
            resources.ApplyResources(this.label10, "label10");
            this.label10.Name = "label10";
            // 
            // label3
            // 
            resources.ApplyResources(this.label3, "label3");
            this.label3.Name = "label3";
            // 
            // _KeepYBox
            // 
            resources.ApplyResources(this._KeepYBox, "_KeepYBox");
            this._KeepYBox.Name = "_KeepYBox";
            this._KeepYBox.UseVisualStyleBackColor = true;
            this._KeepYBox.CheckedChanged += new System.EventHandler(this.Control_ValueChanged);
            // 
            // _PageBox
            // 
            resources.ApplyResources(this._PageBox, "_PageBox");
            this._PageBox.Maximum = new decimal(new int[] {
            9999999,
            0,
            0,
            0});
            this._PageBox.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this._PageBox.Name = "_PageBox";
            this._PageBox.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            // 
            // _KeepXBox
            // 
            resources.ApplyResources(this._KeepXBox, "_KeepXBox");
            this._KeepXBox.Name = "_KeepXBox";
            this._KeepXBox.UseVisualStyleBackColor = true;
            this._KeepXBox.CheckedChanged += new System.EventHandler(this.Control_ValueChanged);
            // 
            // label5
            // 
            resources.ApplyResources(this.label5, "label5");
            this.label5.Name = "label5";
            // 
            // _ZoomRateBox
            // 
            this._ZoomRateBox.FormattingEnabled = true;
            resources.ApplyResources(this._ZoomRateBox, "_ZoomRateBox");
            this._ZoomRateBox.Name = "_ZoomRateBox";
            this._ZoomRateBox.SelectedIndexChanged += new System.EventHandler(this.Control_ValueChanged);
            // 
            // _LeftBox
            // 
            this._LeftBox.DecimalPlaces = 2;
            resources.ApplyResources(this._LeftBox, "_LeftBox");
            this._LeftBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._LeftBox.Minimum = new decimal(new int[] {
            10000,
            0,
            0,
            -2147483648});
            this._LeftBox.Name = "_LeftBox";
            // 
            // label7
            // 
            resources.ApplyResources(this.label7, "label7");
            this.label7.Name = "label7";
            // 
            // _TopBox
            // 
            this._TopBox.DecimalPlaces = 2;
            resources.ApplyResources(this._TopBox, "_TopBox");
            this._TopBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._TopBox.Minimum = new decimal(new int[] {
            10000,
            0,
            0,
            -2147483648});
            this._TopBox.Name = "_TopBox";
            // 
            // label6
            // 
            resources.ApplyResources(this.label6, "label6");
            this.label6.Name = "label6";
            // 
            // _RectanglePanel
            // 
            this._RectanglePanel.Controls.Add(this.label8);
            this._RectanglePanel.Controls.Add(this._WidthBox);
            this._RectanglePanel.Controls.Add(this.label9);
            this._RectanglePanel.Controls.Add(this._HeightBox);
            resources.ApplyResources(this._RectanglePanel, "_RectanglePanel");
            this._RectanglePanel.Name = "_RectanglePanel";
            // 
            // label8
            // 
            resources.ApplyResources(this.label8, "label8");
            this.label8.Name = "label8";
            // 
            // _WidthBox
            // 
            this._WidthBox.DecimalPlaces = 2;
            resources.ApplyResources(this._WidthBox, "_WidthBox");
            this._WidthBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._WidthBox.Name = "_WidthBox";
            // 
            // label9
            // 
            resources.ApplyResources(this.label9, "label9");
            this.label9.Name = "label9";
            // 
            // _HeightBox
            // 
            this._HeightBox.DecimalPlaces = 2;
            resources.ApplyResources(this._HeightBox, "_HeightBox");
            this._HeightBox.Maximum = new decimal(new int[] {
            10000,
            0,
            0,
            0});
            this._HeightBox.Name = "_HeightBox";
            // 
            // _ActionBox
            // 
            this._ActionBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._ActionBox.FormattingEnabled = true;
            resources.ApplyResources(this._ActionBox, "_ActionBox");
            this._ActionBox.Name = "_ActionBox";
            this._ActionBox.SelectedIndexChanged += new System.EventHandler(this.Control_ValueChanged);
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // _TitleBox
            // 
            resources.ApplyResources(this._TitleBox, "_TitleBox");
            this._TitleBox.Name = "_TitleBox";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            resources.ApplyResources(this.tabControl1, "tabControl1");
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this._DefaultOpenBox);
            this.tabPage1.Controls.Add(this._TitleBox);
            this.tabPage1.Controls.Add(this.label2);
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Controls.Add(this._ActionBox);
            this.tabPage1.Controls.Add(this._DestinationPanel);
            this.tabPage1.Controls.Add(this._ScriptBox);
            resources.ApplyResources(this.tabPage1, "tabPage1");
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // _DefaultOpenBox
            // 
            resources.ApplyResources(this._DefaultOpenBox, "_DefaultOpenBox");
            this._DefaultOpenBox.Name = "_DefaultOpenBox";
            this._DefaultOpenBox.UseVisualStyleBackColor = true;
            // 
            // _ScriptBox
            // 
            resources.ApplyResources(this._ScriptBox, "_ScriptBox");
            this._ScriptBox.Controls.Add(this._ScriptContentBox);
            this._ScriptBox.Name = "_ScriptBox";
            this._ScriptBox.TabStop = false;
            // 
            // _ScriptContentBox
            // 
            resources.ApplyResources(this._ScriptContentBox, "_ScriptContentBox");
            this._ScriptContentBox.Name = "_ScriptContentBox";
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this._AttributesBox);
            resources.ApplyResources(this.tabPage2, "tabPage2");
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // _AttributesBox
            // 
            this._AttributesBox.AllColumns.Add(this._AttrNameColumn);
            this._AttributesBox.AllColumns.Add(this._AttrValueColumn);
            this._AttributesBox.CellEditUseWholeCell = false;
            this._AttributesBox.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this._AttrNameColumn,
            this._AttrValueColumn});
            this._AttributesBox.Cursor = System.Windows.Forms.Cursors.Default;
            this._AttributesBox.GridLines = true;
            this._AttributesBox.HideSelection = false;
            resources.ApplyResources(this._AttributesBox, "_AttributesBox");
            this._AttributesBox.Name = "_AttributesBox";
            this._AttributesBox.ShowGroups = false;
            this._AttributesBox.UseCompatibleStateImageBehavior = false;
            this._AttributesBox.View = System.Windows.Forms.View.Details;
            // 
            // _AttrNameColumn
            // 
            resources.ApplyResources(this._AttrNameColumn, "_AttrNameColumn");
            // 
            // _AttrValueColumn
            // 
            this._AttrValueColumn.FillsFreeSpace = true;
            resources.ApplyResources(this._AttrValueColumn, "_AttrValueColumn");
            // 
            // ActionEditorForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.Controls.Add(this.tabControl1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "ActionEditorForm";
            this.ShowInTaskbar = false;
            this._DestinationPanel.ResumeLayout(false);
            this._DestinationPanel.PerformLayout();
            this._PathPanel.ResumeLayout(false);
            this._PathPanel.PerformLayout();
            this._LocationPanel.ResumeLayout(false);
            this._LocationPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this._PageBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._LeftBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._TopBox)).EndInit();
            this._RectanglePanel.ResumeLayout(false);
            this._RectanglePanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this._WidthBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._HeightBox)).EndInit();
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this._ScriptBox.ResumeLayout(false);
            this._ScriptBox.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this._AttributesBox)).EndInit();
            this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.Button _OkButton;
		private System.Windows.Forms.Button _CancelButton;
		private System.Windows.Forms.GroupBox _DestinationPanel;
		private System.Windows.Forms.ComboBox _ActionBox;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.TextBox _TitleBox;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.NumericUpDown _PageBox;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.CheckBox _NewWindowBox;
		private System.Windows.Forms.TextBox _PathBox;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.CheckBox _KeepYBox;
		private System.Windows.Forms.CheckBox _KeepXBox;
		private System.Windows.Forms.ComboBox _ZoomRateBox;
		private System.Windows.Forms.Label label7;
		private System.Windows.Forms.NumericUpDown _TopBox;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.NumericUpDown _LeftBox;
		private System.Windows.Forms.NumericUpDown _HeightBox;
		private System.Windows.Forms.Label label9;
		private System.Windows.Forms.NumericUpDown _WidthBox;
		private System.Windows.Forms.Label label8;
		private System.Windows.Forms.TextBox _NamedBox;
		private System.Windows.Forms.RadioButton _GotoNamedDestBox;
		private System.Windows.Forms.RadioButton _GotoLocationBox;
		private System.Windows.Forms.Panel _LocationPanel;
		private System.Windows.Forms.Panel _PathPanel;
		private System.Windows.Forms.Panel _RectanglePanel;
		private System.Windows.Forms.Label label10;
		private System.Windows.Forms.TabControl tabControl1;
		private System.Windows.Forms.TabPage tabPage1;
		private System.Windows.Forms.TabPage tabPage2;
		private BrightIdeasSoftware.ObjectListView _AttributesBox;
		private BrightIdeasSoftware.OLVColumn _AttrNameColumn;
		private BrightIdeasSoftware.OLVColumn _AttrValueColumn;
		private System.Windows.Forms.TextBox _ScriptContentBox;
		private System.Windows.Forms.GroupBox _ScriptBox;
		private System.Windows.Forms.CheckBox _DefaultOpenBox;
	}
}

