namespace PDFPatcher.Functions.Editor
{
	partial class AddBookmarkConditionForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddBookmarkConditionForm));
            this._MatchFontBox = new System.Windows.Forms.CheckBox();
            this._MatchTextSizeBox = new System.Windows.Forms.CheckBox();
            this._MinSizeBox = new System.Windows.Forms.NumericUpDown();
            this._MaxSizeBox = new System.Windows.Forms.NumericUpDown();
            this.label1 = new System.Windows.Forms.Label();
            this._OkButton = new System.Windows.Forms.Button();
            this._MatchTitlePatternBox = new System.Windows.Forms.CheckBox();
            this._FontListBox = new System.Windows.Forms.ListBox();
            this.label2 = new System.Windows.Forms.Label();
            this._TitleLevelBox = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this._MinSizeBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._MaxSizeBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._TitleLevelBox)).BeginInit();
            this.SuspendLayout();
            // 
            // _MatchFontBox
            // 
            resources.ApplyResources(this._MatchFontBox, "_MatchFontBox");
            this._MatchFontBox.Name = "_MatchFontBox";
            this._MatchFontBox.UseVisualStyleBackColor = true;
            // 
            // _MatchTextSizeBox
            // 
            resources.ApplyResources(this._MatchTextSizeBox, "_MatchTextSizeBox");
            this._MatchTextSizeBox.Name = "_MatchTextSizeBox";
            this._MatchTextSizeBox.UseVisualStyleBackColor = true;
            // 
            // _MinSizeBox
            // 
            this._MinSizeBox.DecimalPlaces = 2;
            resources.ApplyResources(this._MinSizeBox, "_MinSizeBox");
            this._MinSizeBox.Name = "_MinSizeBox";
            this._MinSizeBox.Value = new decimal(new int[] {
            2,
            0,
            0,
            0});
            // 
            // _MaxSizeBox
            // 
            this._MaxSizeBox.DecimalPlaces = 2;
            resources.ApplyResources(this._MaxSizeBox, "_MaxSizeBox");
            this._MaxSizeBox.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this._MaxSizeBox.Name = "_MaxSizeBox";
            this._MaxSizeBox.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            // 
            // _MatchTitlePatternBox
            // 
            resources.ApplyResources(this._MatchTitlePatternBox, "_MatchTitlePatternBox");
            this._MatchTitlePatternBox.Name = "_MatchTitlePatternBox";
            this._MatchTitlePatternBox.UseVisualStyleBackColor = true;
            // 
            // _FontListBox
            // 
            this._FontListBox.FormattingEnabled = true;
            resources.ApplyResources(this._FontListBox, "_FontListBox");
            this._FontListBox.Name = "_FontListBox";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // _TitleLevelBox
            // 
            resources.ApplyResources(this._TitleLevelBox, "_TitleLevelBox");
            this._TitleLevelBox.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this._TitleLevelBox.Name = "_TitleLevelBox";
            this._TitleLevelBox.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            // 
            // AddBookmarkConditionForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._TitleLevelBox);
            this.Controls.Add(this.label2);
            this.Controls.Add(this._FontListBox);
            this.Controls.Add(this._MatchTitlePatternBox);
            this.Controls.Add(this._OkButton);
            this.Controls.Add(this.label1);
            this.Controls.Add(this._MaxSizeBox);
            this.Controls.Add(this._MinSizeBox);
            this.Controls.Add(this._MatchTextSizeBox);
            this.Controls.Add(this._MatchFontBox);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "AddBookmarkConditionForm";
            ((System.ComponentModel.ISupportInitialize)(this._MinSizeBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._MaxSizeBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._TitleLevelBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.CheckBox _MatchFontBox;
		private System.Windows.Forms.CheckBox _MatchTextSizeBox;
		private System.Windows.Forms.NumericUpDown _MinSizeBox;
		private System.Windows.Forms.NumericUpDown _MaxSizeBox;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.Button _OkButton;
		private System.Windows.Forms.CheckBox _MatchTitlePatternBox;
		private System.Windows.Forms.ListBox _FontListBox;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.NumericUpDown _TitleLevelBox;
	}
}
