namespace PDFPatcher.Functions
{
    partial class NewCoordinateEntryForm
    {
        /// <summary>
        /// Required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up all resources in use.
        /// </summary>
        /// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Windows Forms designer

        /// <summary>
        /// Designer supports required methods - Don't
        /// use a code editor to modify the content of this method.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(NewCoordinateEntryForm));
            this._CancelButton = new System.Windows.Forms.Button();
            this._OkButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this._CoordinateBox = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this._AdjustmentAmountBox = new System.Windows.Forms.NumericUpDown();
            this._RelativeBox = new System.Windows.Forms.RadioButton();
            this._AbsoluteBox = new System.Windows.Forms.RadioButton();
            this._ProportionBox = new System.Windows.Forms.RadioButton();
            ((System.ComponentModel.ISupportInitialize)(this._AdjustmentAmountBox)).BeginInit();
            this.SuspendLayout();
            // 
            // _CancelButton
            // 
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // _CoordinateBox
            // 
            this._CoordinateBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._CoordinateBox.FormattingEnabled = true;
            this._CoordinateBox.Items.AddRange(new object[] {
            resources.GetString("_CoordinateBox.Items"),
            resources.GetString("_CoordinateBox.Items1"),
            resources.GetString("_CoordinateBox.Items2"),
            resources.GetString("_CoordinateBox.Items3")});
            resources.ApplyResources(this._CoordinateBox, "_CoordinateBox");
            this._CoordinateBox.Name = "_CoordinateBox";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // _AdjustmentAmountBox
            // 
            this._AdjustmentAmountBox.DecimalPlaces = 2;
            resources.ApplyResources(this._AdjustmentAmountBox, "_AdjustmentAmountBox");
            this._AdjustmentAmountBox.Maximum = new decimal(new int[] {
            1000,
            0,
            0,
            0});
            this._AdjustmentAmountBox.Minimum = new decimal(new int[] {
            1000,
            0,
            0,
            -2147483648});
            this._AdjustmentAmountBox.Name = "_AdjustmentAmountBox";
            // 
            // _RelativeBox
            // 
            resources.ApplyResources(this._RelativeBox, "_RelativeBox");
            this._RelativeBox.Checked = true;
            this._RelativeBox.Name = "_RelativeBox";
            this._RelativeBox.TabStop = true;
            this._RelativeBox.UseVisualStyleBackColor = true;
            // 
            // _AbsoluteBox
            // 
            resources.ApplyResources(this._AbsoluteBox, "_AbsoluteBox");
            this._AbsoluteBox.Name = "_AbsoluteBox";
            this._AbsoluteBox.UseVisualStyleBackColor = true;
            // 
            // _ProportionBox
            // 
            resources.ApplyResources(this._ProportionBox, "_ProportionBox");
            this._ProportionBox.Name = "_ProportionBox";
            this._ProportionBox.TabStop = true;
            this._ProportionBox.UseVisualStyleBackColor = true;
            // 
            // NewCoordinateEntryForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._ProportionBox);
            this.Controls.Add(this._AbsoluteBox);
            this.Controls.Add(this._RelativeBox);
            this.Controls.Add(this._AdjustmentAmountBox);
            this.Controls.Add(this.label2);
            this.Controls.Add(this._CoordinateBox);
            this.Controls.Add(this.label1);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "NewCoordinateEntryForm";
            ((System.ComponentModel.ISupportInitialize)(this._AdjustmentAmountBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button _CancelButton;
        private System.Windows.Forms.Button _OkButton;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox _CoordinateBox;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.NumericUpDown _AdjustmentAmountBox;
        private System.Windows.Forms.RadioButton _RelativeBox;
        private System.Windows.Forms.RadioButton _AbsoluteBox;
        private System.Windows.Forms.RadioButton _ProportionBox;
    }
}
