namespace PDFPatcher.Functions.Editor
{
	partial class PagePropertyForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PagePropertyForm));
            this._CloseButton = new System.Windows.Forms.Button();
            this._PageDimensionBox = new System.Windows.Forms.ListBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this._TopBox = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this._RightBox = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this._BottomBox = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this._LeftBox = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this._RotationBox = new System.Windows.Forms.TextBox();
            this._MainTab = new System.Windows.Forms.TabControl();
            this._DimensionPage = new System.Windows.Forms.TabPage();
            this.label9 = new System.Windows.Forms.Label();
            this._HeightBox = new System.Windows.Forms.TextBox();
            this._WidthBox = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this._TextStylePage = new System.Windows.Forms.TabPage();
            this._TextStyleBox = new BrightIdeasSoftware.ObjectListView();
            this._FontNameColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this._SizeColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this.label7 = new System.Windows.Forms.Label();
            this._MainTab.SuspendLayout();
            this._DimensionPage.SuspendLayout();
            this._TextStylePage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this._TextStyleBox)).BeginInit();
            this.SuspendLayout();
            // 
            // _CloseButton
            // 
            resources.ApplyResources(this._CloseButton, "_CloseButton");
            this._CloseButton.Name = "_CloseButton";
            this._CloseButton.UseVisualStyleBackColor = true;
            // 
            // _PageDimensionBox
            // 
            this._PageDimensionBox.FormattingEnabled = true;
            resources.ApplyResources(this._PageDimensionBox, "_PageDimensionBox");
            this._PageDimensionBox.Name = "_PageDimensionBox";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // _TopBox
            // 
            resources.ApplyResources(this._TopBox, "_TopBox");
            this._TopBox.Name = "_TopBox";
            this._TopBox.ReadOnly = true;
            // 
            // label3
            // 
            resources.ApplyResources(this.label3, "label3");
            this.label3.Name = "label3";
            // 
            // _RightBox
            // 
            resources.ApplyResources(this._RightBox, "_RightBox");
            this._RightBox.Name = "_RightBox";
            this._RightBox.ReadOnly = true;
            // 
            // label4
            // 
            resources.ApplyResources(this.label4, "label4");
            this.label4.Name = "label4";
            // 
            // _BottomBox
            // 
            resources.ApplyResources(this._BottomBox, "_BottomBox");
            this._BottomBox.Name = "_BottomBox";
            this._BottomBox.ReadOnly = true;
            // 
            // label5
            // 
            resources.ApplyResources(this.label5, "label5");
            this.label5.Name = "label5";
            // 
            // _LeftBox
            // 
            resources.ApplyResources(this._LeftBox, "_LeftBox");
            this._LeftBox.Name = "_LeftBox";
            this._LeftBox.ReadOnly = true;
            // 
            // label6
            // 
            resources.ApplyResources(this.label6, "label6");
            this.label6.Name = "label6";
            // 
            // _RotationBox
            // 
            resources.ApplyResources(this._RotationBox, "_RotationBox");
            this._RotationBox.Name = "_RotationBox";
            this._RotationBox.ReadOnly = true;
            // 
            // _MainTab
            // 
            resources.ApplyResources(this._MainTab, "_MainTab");
            this._MainTab.Controls.Add(this._DimensionPage);
            this._MainTab.Controls.Add(this._TextStylePage);
            this._MainTab.Name = "_MainTab";
            this._MainTab.SelectedIndex = 0;
            // 
            // _DimensionPage
            // 
            this._DimensionPage.Controls.Add(this._PageDimensionBox);
            this._DimensionPage.Controls.Add(this._RotationBox);
            this._DimensionPage.Controls.Add(this.label1);
            this._DimensionPage.Controls.Add(this.label6);
            this._DimensionPage.Controls.Add(this.label9);
            this._DimensionPage.Controls.Add(this.label2);
            this._DimensionPage.Controls.Add(this._LeftBox);
            this._DimensionPage.Controls.Add(this._HeightBox);
            this._DimensionPage.Controls.Add(this._TopBox);
            this._DimensionPage.Controls.Add(this.label5);
            this._DimensionPage.Controls.Add(this._WidthBox);
            this._DimensionPage.Controls.Add(this.label4);
            this._DimensionPage.Controls.Add(this.label8);
            this._DimensionPage.Controls.Add(this._RightBox);
            this._DimensionPage.Controls.Add(this.label3);
            this._DimensionPage.Controls.Add(this._BottomBox);
            resources.ApplyResources(this._DimensionPage, "_DimensionPage");
            this._DimensionPage.Name = "_DimensionPage";
            this._DimensionPage.UseVisualStyleBackColor = true;
            // 
            // label9
            // 
            resources.ApplyResources(this.label9, "label9");
            this.label9.Name = "label9";
            // 
            // _HeightBox
            // 
            resources.ApplyResources(this._HeightBox, "_HeightBox");
            this._HeightBox.Name = "_HeightBox";
            this._HeightBox.ReadOnly = true;
            // 
            // _WidthBox
            // 
            resources.ApplyResources(this._WidthBox, "_WidthBox");
            this._WidthBox.Name = "_WidthBox";
            this._WidthBox.ReadOnly = true;
            // 
            // label8
            // 
            resources.ApplyResources(this.label8, "label8");
            this.label8.Name = "label8";
            // 
            // _TextStylePage
            // 
            this._TextStylePage.Controls.Add(this._TextStyleBox);
            this._TextStylePage.Controls.Add(this.label7);
            resources.ApplyResources(this._TextStylePage, "_TextStylePage");
            this._TextStylePage.Name = "_TextStylePage";
            this._TextStylePage.UseVisualStyleBackColor = true;
            // 
            // _TextStyleBox
            // 
            this._TextStyleBox.AllColumns.Add(this._FontNameColumn);
            this._TextStyleBox.AllColumns.Add(this._SizeColumn);
            this._TextStyleBox.CellEditUseWholeCell = false;
            this._TextStyleBox.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this._FontNameColumn,
            this._SizeColumn});
            this._TextStyleBox.Cursor = System.Windows.Forms.Cursors.Default;
            this._TextStyleBox.HideSelection = false;
            resources.ApplyResources(this._TextStyleBox, "_TextStyleBox");
            this._TextStyleBox.Name = "_TextStyleBox";
            this._TextStyleBox.ShowGroups = false;
            this._TextStyleBox.UseCompatibleStateImageBehavior = false;
            this._TextStyleBox.View = System.Windows.Forms.View.Details;
            // 
            // _FontNameColumn
            // 
            resources.ApplyResources(this._FontNameColumn, "_FontNameColumn");
            // 
            // _SizeColumn
            // 
            resources.ApplyResources(this._SizeColumn, "_SizeColumn");
            // 
            // label7
            // 
            resources.ApplyResources(this.label7, "label7");
            this.label7.Name = "label7";
            // 
            // PagePropertyForm
            // 
            this.AcceptButton = this._CloseButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._MainTab);
            this.Controls.Add(this._CloseButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "PagePropertyForm";
            this.ShowInTaskbar = false;
            this._MainTab.ResumeLayout(false);
            this._DimensionPage.ResumeLayout(false);
            this._DimensionPage.PerformLayout();
            this._TextStylePage.ResumeLayout(false);
            this._TextStylePage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this._TextStyleBox)).EndInit();
            this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.Button _CloseButton;
		private System.Windows.Forms.ListBox _PageDimensionBox;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.TextBox _TopBox;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.TextBox _RightBox;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.TextBox _BottomBox;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.TextBox _LeftBox;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.TextBox _RotationBox;
		private System.Windows.Forms.TabControl _MainTab;
		private System.Windows.Forms.TabPage _DimensionPage;
		private System.Windows.Forms.TabPage _TextStylePage;
		private BrightIdeasSoftware.ObjectListView _TextStyleBox;
		private System.Windows.Forms.Label label7;
		private BrightIdeasSoftware.OLVColumn _FontNameColumn;
		private BrightIdeasSoftware.OLVColumn _SizeColumn;
		private System.Windows.Forms.Label label9;
		private System.Windows.Forms.TextBox _HeightBox;
		private System.Windows.Forms.TextBox _WidthBox;
		private System.Windows.Forms.Label label8;
	}
}
