namespace PDFPatcher.Functions
{
    partial class SavePdfForm
    {
        /// <summary>
        /// Required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up all resources in use.
        /// </summary>
        /// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Windows Forms designer

        /// <summary>
        /// Designer supports required methods - Don't
        /// use a code editor to modify the content of this method.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SavePdfForm));
            this._OkButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this._MessageLabel = new System.Windows.Forms.Label();
            this._SourceFileBox = new PDFPatcher.SourceFileControl();
            this._TargetFileBox = new PDFPatcher.TargetFileControl();
            this._ConfigButton = new System.Windows.Forms.Button();
            this._OverwriteBox = new System.Windows.Forms.CheckBox();
            this.SuspendLayout();
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // _CancelButton
            // 
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // _MessageLabel
            // 
            resources.ApplyResources(this._MessageLabel, "_MessageLabel");
            this._MessageLabel.Name = "_MessageLabel";
            // 
            // _SourceFileBox
            // 
            resources.ApplyResources(this._SourceFileBox, "_SourceFileBox");
            this._SourceFileBox.Name = "_SourceFileBox";
            // 
            // _TargetFileBox
            // 
            resources.ApplyResources(this._TargetFileBox, "_TargetFileBox");
            this._TargetFileBox.Name = "_TargetFileBox";
            // 
            // _ConfigButton
            // 
            resources.ApplyResources(this._ConfigButton, "_ConfigButton");
            this._ConfigButton.Image = global::PDFPatcher.Properties.Resources.PdfOptions;
            this._ConfigButton.Name = "_ConfigButton";
            this._ConfigButton.UseVisualStyleBackColor = true;
            // 
            // _OverwriteBox
            // 
            resources.ApplyResources(this._OverwriteBox, "_OverwriteBox");
            this._OverwriteBox.Name = "_OverwriteBox";
            this._OverwriteBox.UseVisualStyleBackColor = true;
            // 
            // SavePdfForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._OverwriteBox);
            this.Controls.Add(this._ConfigButton);
            this.Controls.Add(this._TargetFileBox);
            this.Controls.Add(this._SourceFileBox);
            this.Controls.Add(this._MessageLabel);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "SavePdfForm";
            this.Load += new System.EventHandler(this.ImportBookmarkForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button _OkButton;
        private System.Windows.Forms.Button _CancelButton;
        private System.Windows.Forms.Label _MessageLabel;
        private SourceFileControl _SourceFileBox;
        private TargetFileControl _TargetFileBox;
        private System.Windows.Forms.Button _ConfigButton;
        private System.Windows.Forms.CheckBox _OverwriteBox;
    }
}

