namespace PDFPatcher.Functions
{
	partial class ShiftPageNumberEntryForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            this._OkButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this._MessageLabel = new System.Windows.Forms.Label();
            this._ShiftNumberBox = new System.Windows.Forms.NumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this._ShiftNumberBox)).BeginInit();
            this.SuspendLayout();
            // 
            // _OkButton
            // 
            this._OkButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this._OkButton.Location = new System.Drawing.Point(200, 78);
            this._OkButton.Name = "_OkButton";
            this._OkButton.Size = new System.Drawing.Size(75, 25);
            this._OkButton.TabIndex = 0;
            this._OkButton.Text = "&OK";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // _CancelButton
            // 
            this._CancelButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Location = new System.Drawing.Point(281, 78);
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.Size = new System.Drawing.Size(75, 25);
            this._CancelButton.TabIndex = 1;
            this._CancelButton.Text = "&Cancel";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // _MessageLabel
            // 
            this._MessageLabel.AutoSize = true;
            this._MessageLabel.Location = new System.Drawing.Point(12, 29);
            this._MessageLabel.Name = "_MessageLabel";
            this._MessageLabel.Size = new System.Drawing.Size(270, 39);
            this._MessageLabel.TabIndex = 2;
            this._MessageLabel.Text = "Enter the number of pages to increase or decrease here\r\n (positive numbers increa" +
    "se page numbers, \r\nnegative numbers decrease page numbers):";
            // 
            // _ShiftNumberBox
            // 
            this._ShiftNumberBox.Location = new System.Drawing.Point(288, 39);
            this._ShiftNumberBox.Maximum = new decimal(new int[] {
            999,
            0,
            0,
            0});
            this._ShiftNumberBox.Minimum = new decimal(new int[] {
            999,
            0,
            0,
            -2147483648});
            this._ShiftNumberBox.Name = "_ShiftNumberBox";
            this._ShiftNumberBox.Size = new System.Drawing.Size(68, 20);
            this._ShiftNumberBox.TabIndex = 3;
            this._ShiftNumberBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // ShiftPageNumberEntryForm
            // 
            this.AcceptButton = this._OkButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.ClientSize = new System.Drawing.Size(379, 115);
            this.Controls.Add(this._ShiftNumberBox);
            this.Controls.Add(this._MessageLabel);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "ShiftPageNumberEntryForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Increase or reduce page number";
            this.Load += new System.EventHandler(this.ShiftPageNumberEntryForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this._ShiftNumberBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _OkButton;
		private System.Windows.Forms.Button _CancelButton;
		private System.Windows.Forms.Label _MessageLabel;
		private System.Windows.Forms.NumericUpDown _ShiftNumberBox;
	}
}

