namespace PDFPatcher.Functions
{
	partial class ZoomRateEntryForm
	{
		/// <summary>
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ZoomRateEntryForm));
            this._OkButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this._MessageLabel = new System.Windows.Forms.Label();
            this._ZoomRateBox = new System.Windows.Forms.ComboBox();
            this.SuspendLayout();
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // _CancelButton
            // 
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // _MessageLabel
            // 
            resources.ApplyResources(this._MessageLabel, "_MessageLabel");
            this._MessageLabel.Name = "_MessageLabel";
            // 
            // _ZoomRateBox
            // 
            this._ZoomRateBox.FormattingEnabled = true;
            this._ZoomRateBox.Items.AddRange(new object[] {
            resources.GetString("_ZoomRateBox.Items"),
            resources.GetString("_ZoomRateBox.Items1"),
            resources.GetString("_ZoomRateBox.Items2"),
            resources.GetString("_ZoomRateBox.Items3"),
            resources.GetString("_ZoomRateBox.Items4"),
            resources.GetString("_ZoomRateBox.Items5"),
            resources.GetString("_ZoomRateBox.Items6"),
            resources.GetString("_ZoomRateBox.Items7"),
            resources.GetString("_ZoomRateBox.Items8"),
            resources.GetString("_ZoomRateBox.Items9"),
            resources.GetString("_ZoomRateBox.Items10"),
            resources.GetString("_ZoomRateBox.Items11"),
            resources.GetString("_ZoomRateBox.Items12"),
            resources.GetString("_ZoomRateBox.Items13"),
            resources.GetString("_ZoomRateBox.Items14")});
            resources.ApplyResources(this._ZoomRateBox, "_ZoomRateBox");
            this._ZoomRateBox.Name = "_ZoomRateBox";
            // 
            // ZoomRateEntryForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._ZoomRateBox);
            this.Controls.Add(this._MessageLabel);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "ZoomRateEntryForm";
            this.Load += new System.EventHandler(this.ZoomRateEntryForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _OkButton;
		private System.Windows.Forms.Button _CancelButton;
		private System.Windows.Forms.Label _MessageLabel;
		private System.Windows.Forms.ComboBox _ZoomRateBox;
	}
}

