namespace PDFPatcher.Functions
{
	partial class FontFilterForm
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean all the resources being used.
		/// </summary>
		/// <param name="disposing">true if the managed resource should be released; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Code generated by the Windows Forms designer

		/// <summary>
		/// Designer supports required methods - Don't
		/// use a code editor to modify the content of this method.
		/// </summary>
		private void InitializeComponent () {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FontFilterForm));
            this._OkButton = new System.Windows.Forms.Button();
            this._CancelButton = new System.Windows.Forms.Button();
            this._MessageLabel = new System.Windows.Forms.Label();
            this._FontNameSizeColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this._FirstPageColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this._CountColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this._FontInfoBox = new BrightIdeasSoftware.TreeListView();
            this._AddFilterMenu = new System.Windows.Forms.ContextMenuStrip(this.components);
            this._FilterBox = new BrightIdeasSoftware.ObjectListView();
            this._ConditionColumn = ((BrightIdeasSoftware.OLVColumn)(new BrightIdeasSoftware.OLVColumn()));
            this._AddConditionButton = new System.Windows.Forms.Button();
            this._RemoveConditionButton = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this._FontInfoBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._FilterBox)).BeginInit();
            this.SuspendLayout();
            // 
            // _OkButton
            // 
            resources.ApplyResources(this._OkButton, "_OkButton");
            this._OkButton.Name = "_OkButton";
            this._OkButton.UseVisualStyleBackColor = true;
            this._OkButton.Click += new System.EventHandler(this._OkButton_Click);
            // 
            // _CancelButton
            // 
            resources.ApplyResources(this._CancelButton, "_CancelButton");
            this._CancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._CancelButton.Name = "_CancelButton";
            this._CancelButton.UseVisualStyleBackColor = true;
            this._CancelButton.Click += new System.EventHandler(this._CancelButton_Click);
            // 
            // _MessageLabel
            // 
            resources.ApplyResources(this._MessageLabel, "_MessageLabel");
            this._MessageLabel.Name = "_MessageLabel";
            // 
            // _FontNameSizeColumn
            // 
            resources.ApplyResources(this._FontNameSizeColumn, "_FontNameSizeColumn");
            // 
            // _FirstPageColumn
            // 
            this._FirstPageColumn.HeaderTextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            resources.ApplyResources(this._FirstPageColumn, "_FirstPageColumn");
            // 
            // _CountColumn
            // 
            this._CountColumn.HeaderTextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            resources.ApplyResources(this._CountColumn, "_CountColumn");
            // 
            // _FontInfoBox
            // 
            this._FontInfoBox.AllColumns.Add(this._FontNameSizeColumn);
            this._FontInfoBox.AllColumns.Add(this._FirstPageColumn);
            this._FontInfoBox.AllColumns.Add(this._CountColumn);
            resources.ApplyResources(this._FontInfoBox, "_FontInfoBox");
            this._FontInfoBox.CellEditUseWholeCell = false;
            this._FontInfoBox.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this._FontNameSizeColumn,
            this._FirstPageColumn,
            this._CountColumn});
            this._FontInfoBox.ContextMenuStrip = this._AddFilterMenu;
            this._FontInfoBox.FullRowSelect = true;
            this._FontInfoBox.GridLines = true;
            this._FontInfoBox.HeaderWordWrap = true;
            this._FontInfoBox.HideSelection = false;
            this._FontInfoBox.MultiSelect = false;
            this._FontInfoBox.Name = "_FontInfoBox";
            this._FontInfoBox.ShowGroups = false;
            this._FontInfoBox.UseCompatibleStateImageBehavior = false;
            this._FontInfoBox.View = System.Windows.Forms.View.Details;
            this._FontInfoBox.VirtualMode = true;
            // 
            // _AddFilterMenu
            // 
            this._AddFilterMenu.ImageScalingSize = new System.Drawing.Size(20, 20);
            this._AddFilterMenu.Name = "_AddFilterMenu";
            this._AddFilterMenu.ShowImageMargin = false;
            resources.ApplyResources(this._AddFilterMenu, "_AddFilterMenu");
            this._AddFilterMenu.Opening += new System.ComponentModel.CancelEventHandler(this._AddFilterMenu_Opening);
            this._AddFilterMenu.ItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this._AddFilterMenu_ItemClicked);
            // 
            // _FilterBox
            // 
            this._FilterBox.AllColumns.Add(this._ConditionColumn);
            resources.ApplyResources(this._FilterBox, "_FilterBox");
            this._FilterBox.CellEditUseWholeCell = false;
            this._FilterBox.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this._ConditionColumn});
            this._FilterBox.Cursor = System.Windows.Forms.Cursors.Default;
            this._FilterBox.FullRowSelect = true;
            this._FilterBox.GridLines = true;
            this._FilterBox.HideSelection = false;
            this._FilterBox.Name = "_FilterBox";
            this._FilterBox.ShowGroups = false;
            this._FilterBox.UseCompatibleStateImageBehavior = false;
            this._FilterBox.View = System.Windows.Forms.View.Details;
            // 
            // _ConditionColumn
            // 
            resources.ApplyResources(this._ConditionColumn, "_ConditionColumn");
            // 
            // _AddConditionButton
            // 
            resources.ApplyResources(this._AddConditionButton, "_AddConditionButton");
            this._AddConditionButton.Name = "_AddConditionButton";
            this._AddConditionButton.UseVisualStyleBackColor = true;
            this._AddConditionButton.Click += new System.EventHandler(this.ControlEvent);
            // 
            // _RemoveConditionButton
            // 
            resources.ApplyResources(this._RemoveConditionButton, "_RemoveConditionButton");
            this._RemoveConditionButton.Name = "_RemoveConditionButton";
            this._RemoveConditionButton.UseVisualStyleBackColor = true;
            this._RemoveConditionButton.Click += new System.EventHandler(this.ControlEvent);
            // 
            // FontFilterForm
            // 
            this.AcceptButton = this._OkButton;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._CancelButton;
            this.Controls.Add(this._RemoveConditionButton);
            this.Controls.Add(this._AddConditionButton);
            this.Controls.Add(this._FontInfoBox);
            this.Controls.Add(this._MessageLabel);
            this.Controls.Add(this._FilterBox);
            this.Controls.Add(this._CancelButton);
            this.Controls.Add(this._OkButton);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FontFilterForm";
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
            this.Load += new System.EventHandler(this.FontFilterForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this._FontInfoBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._FilterBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _OkButton;
		private System.Windows.Forms.Button _CancelButton;
		private System.Windows.Forms.Label _MessageLabel;
		private BrightIdeasSoftware.OLVColumn _FontNameSizeColumn;
		private BrightIdeasSoftware.OLVColumn _FirstPageColumn;
		private BrightIdeasSoftware.OLVColumn _CountColumn;
		private BrightIdeasSoftware.TreeListView _FontInfoBox;
		private System.Windows.Forms.ContextMenuStrip _AddFilterMenu;
		private BrightIdeasSoftware.ObjectListView _FilterBox;
		private BrightIdeasSoftware.OLVColumn _ConditionColumn;
		private System.Windows.Forms.Button _AddConditionButton;
		private System.Windows.Forms.Button _RemoveConditionButton;
	}
}

